### ISSUE TITLE
Reinstate alert thresholds

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#112]
**Why is this needed**:

So the reason for alerts is easily, intuitively known. Can no longer see eg

![image](https://github.com/grafana/grafana/assets/5072156/e815a7e2-69d2-4b35-abb2-0758a50b5dea)

**What would you like to be added**:

Alert thresholds. Disappeared in a recent version when Grafana switched from "graph" chart panel type to new "timeseries" type.

**Who is this feature for?**

People who use alerts.

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/78748

**Comment by moxious** [comment]
**Elaboration**: 
  
Hello @tonypowa, 

Thanks for reporting the issue with Grafana's switch from "graph" chart panel type to the new "timeseries" type. To ensure that we fully understand the problem and thus be able to address your concerns effectively, could you please provide us with some additional information?

1. **Version of Grafana:** Can you specify the version number of Grafana where you observed the disappearance of alert thresholds?
2. **Steps to Reproduce:** Could you give us step-by-step instructions on how to recreate the issue, starting with how alert thresholds were set up in the previous version and what changes were noticed after the update?
3. **Expected vs. Actual Behavior:** What is the expected behavior of alert thresholds on the new "timeseries" type, and what are you currently observing?
4. **Configuration Details:** Are there any particular configuration settings that you were using that could assist us in recreating the environment?
5. **Error Logs/Screenshots:** If applicable, are there any error logs or console messages when trying to use alert thresholds? Additional screenshots demonstrating the before and after could be very helpful.

Providing the above information will help us to better understand and resolve the issue you are facing.

Thanks for your contribution to the community, and we're looking forward to your response!

**Meta**:

**Comment by moxious** [comment]
**Triage summary**: Request to reinstate alert thresholds in Grafana, which became missing after switch from the 'graph' chart panel type to the new 'timeseries' type; impacting the users who utilize alerts.

**Recommended labels**:

area/alerting
type/feature-request
