### ISSUE TITLE
Dashboard settings can be modified and changes are reflected when navigating back to a dashboard.

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#129]

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78735

**Comment by moxious** [comment]
Thank you for your contribution! It sounds like you're referring to an issue with dashboard behaviors in Grafana. To ensure that the appropriate team can address this, I'm tagging the **Dashboards Sharing squad project** as they are responsible for managing dashboard settings and user interactions within the dashboards.

**Meta**:

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa! 👋 Thanks for your contribution to the project! It seems like your issue does not contain any description of the problem or the steps to reproduce it. Could you please update the issue with a detailed explanation? This will greatly help us in understanding the issue better and addressing it effectively. 🛠️

Meanwhile, here's a little joke to brighten your day:

> How does a computer get drunk?
> It takes screenshots. 🖥️🍸

Looking forward to your update!

**Meta**:

**Comment by moxious** [comment]
**Elaboration**: 
  
Hello @tonypowa, thank you for taking the time to contribute to the project by opening an issue. However, in order to best assist you and ensure that we can reproduce and understand the issue, we need a bit more detail on the problem you're experiencing. Could you please provide us with the following information?:

- What are the steps to reproduce the issue you're observing? This includes the initial state of the dashboard, the modifications you make, and how you navigate back.
- What is the expected behavior and what is the actual behavior you're experiencing after making the modifications and navigating back?
- Are there any error messages or unusual behaviors that you notice when the issue occurs?
- Could you tell us which version of the software you're using, as well as your operating system and browser details if applicable?
- If possible, a screenshot or screen recording showing the issue could be incredibly helpful.
- Are there any specific settings or configurations that you believe may be relevant to this issue?

Once we have this information, we'll be better positioned to address your concern. Looking forward to your response!

**Meta**:
