### ISSUE TITLE
Panel cannot click the copy button of the sharing link in ifream

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#138]
### What happened?

Panel cannot click the copy button of the sharing link in ifream

### What did you expect to happen?

Panel cannot click the copy button of the sharing link in ifream

### Did this work before?

Place Grafana in ifream

### How do we reproduce it?

1.Place Grafana in ifream

2.Select Panel click share

3.Click Link Copy Button

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:v9.5.13

OS:Linux

Browser:Google Chrome v119.0.6045.124

 

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78519

**Comment by moxious** [comment]
Hi @tonypowa, it sounds like you're experiencing an issue with sharing links from a panel within an iframe on the Grafana UI. This seems to be related to the **Frontend Platform project**, as it is concerned with the user interface components and their behaviors within Grafana. I'm suggesting this as the best fit, so the frontend team can investigate the issue with embedding Grafana in an iframe and the interaction with sharing links.

Make sure to provide any additional details or errors observed in browser's console to help with troubleshooting. If you believe this is related to a specific panel type provided by a plugin, please specify it as well.

**Meta**:

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa! 👋 Thanks for reporting this issue. It seems like you're having trouble with interaction within an iframe, specifically when trying to copy a sharing link. I'll look into this and get back to you as soon as possible. In the meantime, keep in mind that some actions in iframes may be restricted due to browser security policies, such as the [Same-Origin Policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). Just to lighten the mood while we investigate the issue, here's a little joke for you 😄:

**Knock knock!**
*Who’s there?*
**Control Freak.**
*Con...*
**Okay, now you say, 'Control Freak who?'**

Don't worry, we'll handle this issue no matter who's in control! 😉

**Meta**:

**Comment by moxious** [comment]
**Triage summary**: The user is unable to click the copy button for the sharing link of a panel when Grafana is placed inside an iframe. The expected behavior is unclear, as the user has mentioned the issue twice without stating what should happen when the copy button is clicked.

**Recommended labels**:

area/panel/share
type/bug

**Comment by moxious** [comment]
**Elaboration**: 
  
Hello @tonypowa, thank you for taking the time to submit an issue. It seems like there is an issue with the copy button function within an iframe — this can indeed be frustrating. To better assist you and address the issue, we need a little more information. Could you please provide the following additional details? 

- Can you confirm if the copy button works as expected outside of the iframe?
- Are there any console errors in the browser when you attempt to click the copy button? To check this, please open the browser's developer tools (usually F12) and navigate to the 'Console' tab.
- Could you provide details on any specific configuration you have for Grafana or the iframe that might be relevant to this issue?
- Have you made any customizations to the Grafana instance or are you using any plugins that could affect this interaction?
- Does the issue occur for all users and on all browsers, or is it isolated to a specific scenario?
- If possible, could you provide a screenshot or video demonstrating the issue?

Your responses to these questions will help us pinpoint the problem more accurately and work toward a solution. We appreciate your cooperation!

**Meta**:

**Comment by tonypowa** [comment]
thanks for

if possible, could you provide a screenshot or video demonstrating the issue?

Are there any console errors in the browser when you attempt to click the copy button? To check this, please open the browser's developer tools (usually F12) and navigate to the 'Console' tab.
