### ISSUE TITLE
Add option to display dashboards without any authorization/authentication (just like they were in 8.X)

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#147]
**Why is this needed**:

We want to have a set of public dashboards (CNCF/DevStats) that should be available for anybody, always, no authentication/authorization of any kind is needed - this was working just fine with 8.X using anonymous user and then stopped with 9.X, 10.X. Dashboards use read-only database connection and they only access publicly available data - it is not related to any particular user.

**What would you like to be added**:

Support to display dashboards without checking any permissions so there is no longer an error like "you need to have 'dashboards:read' permission to access this" or anything similar. We want to allow anonymous access to dashboards.

**Who is this feature for?**

- [CNCF/DevStats](https://k8s.devstats.cncf.io).

**There is a bug already reported for this**

I've reported this bug a long time back: https://github.com/grafana/grafana/issues/54974

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78639

**Comment by moxious** [comment]
**Triage summary**: The issue requests reintroducing the ability to display dashboards publicly without any form of authentication or authorization, a feature that was available in Grafana 8.X but removed in later versions. The user specifies the need for this feature to enable public access to CNCF/DevStats dashboards.

**Recommended labels**:

area/auth
type/feature-request

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa! 👋 

Thank you for contributing your idea about reintroducing public dashboard access without authentication. Considering the use case with CNCF/DevStats, the need for public dashboards is clear. The team will discuss the feasibility of bringing back the feature from 8.X in the context of the newer versions. We'll update this issue once we have more information.

 Meanwhile, speaking of public access, here's something to lighten the mood while we delve into the issue:

> Knock knock.
> *Who's there?*
> Lettuce. 
> *Lettuce who?*
> Lettuce in, it's cold out here! 🥬😄

We'll make sure to not keep you waiting in the cold for this feature request update! 😉

Stay tuned!

**Meta**:

**Comment by moxious** [comment]
Hi @tonypowa, it seems your request is closely related to the Grafana core functionality concerning dashboards and authentication. This typically falls under the **Backend platform project**. I will forward this issue to the team responsible for backend services to consider the reintroduction of the feature of public dashboards without authentication, which is integral for public data viewing like CNCF/DevStats.

/reference #54974 for tracking the related bug.

**Meta**:

**Comment by moxious** [comment]
**Elaboration**: 
  
Thank you for submitting your issue and providing details on what you need. The description of the functionality that you're asking for is clear, but to help our developers address your request effectively, we could use some more information. Could you please provide some additional details to help us better understand the situation? 

- Since you mentioned the feature was working fine in 8.X but stopped with subsequent releases, could you specify the exact version when this issue first appeared?
- Have there been any changes to the configuration or setup alongside the upgrade that might have affected this feature?
- You've referenced a reported bug. Has there been any interim solution or workaround that you've tried to apply while waiting for the feature to be restored?
- If there were any error messages or logs when you encountered the 'dashboards:read' permission error, could you please share them?
- And finally, could you describe the expected user flow for accessing the dashboards without authorization/authentication in a bit more detail? For example, how should the redirection to the public dashboard work in the absence of a logged-in user session?

This additional information will greatly assist our development team in reproducing the issue and devising a solution that aligns with your needs.

**Meta**:
