### ISSUE TITLE
Google Cloud Monitoring Multivalue variables not working in PromQL Queries

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#148]
### What happened?

When I create a variable that allows multiple selections and attempt to include it in a PromQL query such as foo{label~="$values"} it becomes:

foo{label~="{bar,baz}"}

This is not valid PromQL and the query returns empty.

The correct way would be to use foo{label~="bar|baz"} but I have no idea how to instruct the plugin to construct this type of multivalue representation.

### What did you expect to happen?

Multivalue labels to work correctly

### Did this work before?

No

### How do we reproduce it?

1. Create Multivalue Variable based on GCP's Monitoring Label Values equivalent

2. Create Query using multivalue variable

3. Observe blank graph

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

I use Grafana Cloud

### Datasource(s)?

Google Cloud Monitoring 1.0.0

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78619

**Comment by moxious** [comment]
**Triage summary**: Multivalue variables within PromQL queries for Google Cloud Monitoring datasource do not correctly format when querying, causing empty graph results.

**Recommended labels**:

area/datasource
area/grafana/data
datasource/GoogleCloudMonitoring
type/bug

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hello @tonypowa! 👋 First off, here's a lighthearted joke to get us in the problem-solving mood: Why do programmers prefer dark mode? Because light attracts bugs! 😄 Now, onto your issue. It seems like the syntax for the multivalue label in your PromQL query isn't playing nice with Grafana's expected format. You might have more success with a regex match, such as:



Replacing  with the actual variable should end up constructing something like:  which is what you're looking for. As you've mentioned that you don't know how to instruct the plugin to do this, it sounds like a potential enhancement for the plugin's documentation or an additional feature that could be requested. This issue could benefit from input by the plugin maintainers or someone from the community who has faced and solved a similar challenge. Has anyone else in the community encountered and resolved something similar?

In the meantime, if you're able to give a bit more detail about the version of Grafana you're using, alongside the exact steps to create the multivalue variable, it might help others to reproduce the issue and provide more targeted suggestions. 🛠️

**Meta**:

**Comment by moxious** [comment]
**Elaboration**: 
  
Hello @tonypowa,

Thank you for the detailed description of the issue you're encountering with multivalue variables in PromQL queries. To help us address the issue more effectively, could you please provide a few more details?

1. Could you share an example of the variable configuration you are using, specifically showing how the multivalue is set up in Grafana?

2. When constructing the query, are you manually editing the query to include , or are you using Grafana's built-in variable syntax interface?

3. A screenshot of the setup where you define the variable and the query in your Grafana dashboard could be really helpful in understanding the issue better.

4. Can you confirm if you have tried any workarounds or if you found any related issues in the plugin's documentation or community forums?

5. Lastly, could you provide the versions of Grafana, the operating system of the server running it, and the browser you are using?

Having these additional details will help us to replicate the behavior and get to the bottom of this more swiftly.

Looking forward to your response!

**Meta**:

**Comment by tonypowa** [comment]
wrong team but good elaboration 1,3
