### ISSUE TITLE
XY Chart Adjust X axis max

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#149]
### What happened?

Dear grafana community,

on the XY-Chart the limits do not work correctly.

If Min and Max are set individually for the x AND y axis (overrides), it only works for the y axis. In my case the x-axis should also be limited.

### What did you expect to happen?

The overrides on the y-axis work, the max and min are set properly there, but the x axis completely ignores the settings.

### Did this work before?

No

### How do we reproduce it?

N/A

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78616

**Comment by moxious** [comment]
Hi @tonypowa, thank you for reporting this issue. It seems like it's related to the dashboard visualization functionality, which makes it likely a concern for the **DataViz project**. I'll transfer this issue there so the right team can have a look at it.

**Meta**:

**Comment by moxious** [comment]
**Triage summary**: The issue reports a bug in the XY Chart panel where setting individual Min and Max overrides on the X axis does not work as expected, while it functions correctly for the Y axis.

**Recommended labels**:

area/panel/xychart
type/bug

**Comment by moxious** [comment]
**Elaboration**: 
  

Thank you for reaching out with your issue, @tonypowa!

In order to better understand and address the problem you're experiencing with the XY-Chart in Grafana, we require a little more information. Could you please provide the following details?

1. Can you share the specific version of Grafana you are using?
2. What operating system and browser version are you using when encountering this issue?
3. Would it be possible for you to provide a step-by-step guide on how to reproduce the issue starting from a new dashboard? This greatly helps in diagnosing the problem.
4. Are there any specific panel settings or queries that seem related to this issue? If yes, sharing those details or a screenshot might be useful.
5. Have you tried to troubleshoot the issue by checking the browser's developer console for any errors while you attempt to set the overrides for the X-axis?

Providing more context and detailed reproducible steps will aid the community and contributors in understanding the root cause and work towards a resolution for the issue.

Thanks for your collaboration, and we're looking forward to your response to assist you further!

**Meta**:

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa 👋, thanks for reporting this issue! Just to clarify, you're experiencing problems when configuring the Min and Max values for the X-axis on the XY-Chart panel, but it works fine for the Y-axis, correct? It'd be super helpful if you could include a bit more detail on the steps to reproduce the issue, including which data source you're using, as it could be related to how the data source handles the axis limits. While the Grafana team is looking into this, here's something to lighten the mood: 😄

**Joke:** Why do developers prefer dark mode? Because light attracts bugs!

Please follow up with those additional details when you can. The community appreciates your contribution!

P.S. If you happen to have found a workaround or additional info since you posted, let us know!

**Meta**:

**Comment by tonypowa** [comment]
useful elaboration 1-3 !
