### ISSUE TITLE
Y-axis values not easily readable when using logarithmic base 10 scale

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#152]
### What happened?

Created a graph panel with logarithmic base 10 y-axis. The y-axis values are squashed together and unreadable:

![Clipboard03](https://github.com/grafana/grafana/assets/43373700/23c3f7c4-1d28-43f6-bd46-bac25354c7d0)

### What did you expect to happen?

I expected y-axis values to be clearly seperated and readable. 

### Did this work before?

This was the case with previous versions of Grafana (v5):

![Clipboard02](https://github.com/grafana/grafana/assets/43373700/3632b8a6-00de-4ab2-b9af-281aa75a5277)

### How do we reproduce it?

1. Create a graph with logarithmic base 10 yaxis on Grafana v10.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: 10

OS: RedHat

Browser: Firefox

### Grafana platform?

Docker

### Datasource(s)?

InfluxDB

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78585

**Comment by moxious** [comment]
**Triage summary**: The issue describes a regression where the y-axis values displayed on a logarithmic base 10 scale are squashed together and unreadable on Grafana v10, in contrast to previous readability in Grafana v5.

**Recommended labels**:

area/dataviz
type/regression
area/panel/graph

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa, 

Thank you for bringing this to our attention! It looks like you've stumbled upon a scaling issue with the logarithmic y-axis in Grafana v10. Before we relay this to the development team, could you please confirm whether the same behavior occurs with different browsers or just Firefox? Also, have you tried adjusting the axis label step to see if that provides a temporary workaround? 

Meanwhile, the team will look into how this regression from v5 to v10 affected the label readability. If possible, would you be able to provide any console logs or errors that appear when you create the graph? This extra information could help us in diagnosing the issue faster. 

As we work on smoothing out this wrinkle, here's a joke to lighten the mood: 

Why did the scarecrow win an award? 
Because he was outstanding in his field! 🌾

We appreciate your contribution to the community and your patience while we resolve this.

Best,
[Your GitHub Username]

**Meta**:

**Comment by moxious** [comment]
**Elaboration**: 
  
Hello @tonypowa, thank you for bringing this issue to our attention. We want to make sure we address it promptly and correctly. To help us investigate this further, could you please provide us with a few more details?

- When you mention the y-axis values are squashed together and unreadable, could you clarify if there has been a change in the amount of data points or labels displayed compared to the older version?
- Is it possible to attach a screenshot that shows the entire panel, including axis settings, to help visualize the issue in context?
- Could you provide the panel JSON configuration that reproduces this issue?
- Have you noticed if the issue persists across different browsers or is it isolated to Firefox?
- Are there any console errors in your browser's Developer Tools when you observe the y-axis issue?

Once we have this information, it'll be much easier for us to replicate the problem and work towards a solution. Thank you for your collaboration!

**Meta**:
