### ISSUE TITLE
Custom unit entered on the `Unit` field should not be interpreted as a format ID

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#154]
### What happened?

When entering a custom unit in the `Unit` field that coincides with one of the built-in format IDs, it's currently interpreted as a reference to that built-in format, not as the literal input.

For example, I entered `bps` to denote "basis points", a common term in finance https://www.investopedia.com/ask/answers/what-basis-point-bps/

However, it was interpreted as a predefined format ID referring to `bits/sec(SI)`

https://github.com/grafana/grafana/blob/e2f2d8b3d64c9fb2cb9b5771124f181d7eef63b6/packages/grafana-data/src/valueFormats/categories.ts#L176

After some trial & error, I figured I could enter `suffix:bps`. This behavior of interpreting inputs as IDs isn't documented in the Grafana documentation:

https://grafana.com/docs/grafana/latest/panels-visualizations/configure-standard-options/#custom-units

This feature should be either clearly documented or adjusted to prioritize literal interpretation of custom units.

While `BPS` in uppercase does not encounter this issue, I believe we see `bps` (in lowercase) more often in the finance sector.

For those intending to represent "bits per second", they have the option to select it from the dropdown list or enter `b/s`.

![Screenshot 2023-11-21 at 6 02 16 PM](https://github.com/grafana/grafana/assets/90726/53033b93-b508-4cb3-98b8-dae3bc31154d)

![Screenshot 2023-11-21 at 6 02 38 PM](https://github.com/grafana/grafana/assets/90726/4c593fbe-b9bb-427e-a9b2-a4e53035f19a)

### What did you expect to happen?

.

### Did this work before?

.

### How do we reproduce it?

.

### Environment (with versions)?

Grafana v10.2.1 (533a733e4eda44041e43358c5a51203e9b42c9ea)

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78576

**Comment by moxious** [comment]
**Triage summary**: When a custom unit 'bps' is entered in the  field, it's incorrectly interpreted as the format ID 'bits/sec(SI)' instead of 'basis points'. This behavior isn't documented and can cause confusion, suggesting a need for either improved documentation or a change in the logic to prioritize literal input interpretation.

**Recommended labels**:

area/units
type/bug
area/frontend

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hey @tonypowa! 👋 Thanks for reporting this issue with the  field behavior. Knock-knock! Who’s there? Tank. Tank who? You're welcome for me bringing this to the dev team's attention! 😄 In all seriousness, I appreciate you taking the time to provide a detailed explanation and suggesting useful solutions. Your point about clear documentation and the literal interpretation of custom units is well-taken. The unexpected behavior when using common financial terms like  can definitely be confusing and limits the UI's intuitiveness. I've flagged this for the team to consider for future releases. In the meantime, using the  workaround seems to be the best bet. 🛠️ Cheers to making Grafana more flexible for all users in the finance sector and beyond! 📈

**Meta**:

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you've encountered an issue with the interpretation of custom units within Grafana's unit field. Based on the details you've provided, this issue appears to be related to the core functionality of Grafana's front-end, particularly handling custom unit formats. I believe it would be best to associate this issue with the **Frontend Platform project** so the appropriate team can review the behavior of custom units and consider making adjustments to the documentation or functionality. Thank you for bringing this to our attention!

**Meta**:

**Comment by moxious** [comment]
**Elaboration**: 
  
Hello @tonypowa, and thank you for bringing this issue to our attention.

It seems that you've run into an interesting behavior where the  field is mistakenly identifying your custom input as a predefined format ID. It's helpful that you've discovered a workaround using , and also that you have pointed out the lack of documentation on this behavior.

Before we proceed to address this issue further, could you help us by providing the following additional information?

1. **Steps to Reproduce:** You mention there's an issue with interpreting custom unit inputs—can you provide a step-by-step guide that you followed to encounter this problem? This will help us replicate the issue on our end.

2. **Expected vs. Actual Behavior:** I noticed you left the section blank on 'What did you expect to happen?'. Could you clarify what your expected behavior was when you originally entered 'bps' as a custom unit?

3. **Screenshots Issue:** The links to your screenshots appear to be broken or formatted incorrectly. Could you please re-upload those images or provide the correct links? Images can often give crucial context to an issue.

Once we have this information, we'll be in a much better position to understand and resolve the issue effectively. Thank you for your cooperation and contribution to the community!

**Meta**:

**Comment by tonypowa** [comment]
prob not for front end but dashboard team, otherwise GJ!
