### ISSUE TITLE
Panel/Time series: The last value in plot does not match Table view 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#157]
### What happened?

I have a time series panel in Grafana with the Amazon Athena plugin, see below playground:

https://grafana.csselectronics.stellarhosted.com/d/canmod-input/canmod-input-test?from=1699869308000&to=1699869481000&orgId=1

The aim is to show a plot of the average value of a specific signal as per the panel. When setting up the query and looking at the Table View, everything looks as expected (values fluctuating around ~4700-5200 approximately throughout). Notice how in the table view, the last value is showing as 4781, which is as expected:

![image](https://github.com/grafana/grafana/assets/26184427/2be3f381-13d3-45c8-a5a4-288964b837b5)

However, when changing to the Time Series panel view, I get a strange result where the 'max' value of the last aggregation observation is shown, resulting in a strange plot as below:

![image](https://github.com/grafana/grafana/assets/26184427/7c5c999a-0782-4ae1-a2fb-141c5dd24817)

Notice in particular that the last observation is showing as the value 9860 and that the timestamp is 1 second after the Table View last timestamp:

![image](https://github.com/grafana/grafana/assets/26184427/d67122d8-9022-4ca4-9737-cdc34f4c8307)

### What did you expect to happen?

I would expect the Time Series view to produce a plot of the observation timestamps and values that appear in the Table View

### Did this work before?

I'm not sure if this is a new behavior, but I think my particular dataset makes this very visible (it's a sinus style curve where the plots show aggregations from across "long time periods", meaning that the average values at this level become 4700-5100 in range, while the max individual observations are up around 9000-1000.

### How do we reproduce it?

I have provided the panel as an export here:

[debug-message_ can2_analog1to8fd _ signal_ analog5fd -2023-11-24 09_50_36.json.txt](https://github.com/grafana/grafana/files/13456943/debug-message_.can2_analog1to8fd._.signal_.analog5fd.-2023-11-24.09_50_36.json.txt)

### Is the bug inside a dashboard panel?

Yes, the Time Series panel

### Environment (with versions)?

Grafana: Cloud

OS: Windows 10

Browser: Chrome

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78626

**Comment by moxious** [comment]
Hello @tonypowa, thank you for reporting this discrepancy between the table view and the time series panel view. It seems like this could be related to the **Amazon Athena plugin** you are using in conjunction with the Time Series panel. To get the right attention to this issue, I'm directing it towards the **AWS Datasources project**. The team responsible for the plugin will have the needed expertise to investigate the potential query processing or visualization discrepancy you're encountering.

**Meta**:

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa, thanks for reporting this issue! 👋 It seems like you've stumbled upon a rather peculiar divergence in your time series data. Before we dive into the serious stuff, here's a light joke to brighten up the debugging process: 

Why don't scientists trust atoms? Because they make up everything! 😄 

Now, back to business. It appears there could be an issue with how the data aggregation is being handled for the visualization. Have you checked if there are any settings in the panel that might be affecting the aggregation, such as the specified aggregation function (mean, max, etc.)? It might also be useful to examine whether there are any discrepancies in the timestamps of your data points that could cause this. If you have any additional context or can confirm the panel settings, it would greatly help in troubleshooting the issue. Meanwhile, I'll also bring this to the attention of the team for further investigation. 🕵️‍♂️

**Meta**:

**Comment by moxious** [comment]
**Triage summary**: The Time Series panel shows an incorrect 'max' value for the last data point which does not match the expected average value shown in the Table View when using the Amazon Athena plugin.

**Recommended labels**:

area/panel/timeseries
type/bug
datasource/Athena
