### ISSUE TITLE
Grafana-backend: Make Run failing on Windows due to BRA

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#161]
### What happened?

Unable to build Grafana-backend on windows. See following steps and corresponding terminal outputs:

```

$ go install github.com/google/wire/cmd/wire@latest

go: downloading github.com/google/wire v0.5.0

go: downloading github.com/pmezard/go-difflib v1.0.0

go: downloading github.com/google/subcommands v1.0.1

go: downloading golang.org/x/tools v0.0.0-20190422233926-fe54fb35175b

```

```

$ $GOPATH/bin/wire.exe gen -tags oss ./pkg/server ./pkg/cmd/grafana-cli/runner

wire: github.com/grafana/grafana/pkg/server: wrote C:\SB\mm-grafana-ui\pkg\server\wire_gen.go

```

```

$ go run build.go build

Version: 10.1.5, Linux Version: 10.1.5, Package Iteration: 1700841246

building binaries build

building grafana ./pkg/cmd/grafana

rm -r ./bin/windows-amd64/grafana.exe

rm -r ./bin/windows-amd64/grafana.exe.md5

go build -ldflags -w -X main.version=10.1.5 -X main.commit=e9497b96 -X main.buildstamp=1700726600 -X main.buildBranch=ingr_em21_10_dev_temp_grafana_lcm -buildmode=exe -o ./bin/windows-amd64/grafana.exe ./pkg/cmd/grafana

go: downloading github.com/urfave/cli/v2 v2.25.0

go: downloading github.com/xrash/smetrics v0.0.0-20201216005158-039620a65673

go version

go version go1.20.3 windows/amd64

Targeting windows/amd64

building binaries build

building grafana-server ./pkg/cmd/grafana-server

rm -r ./bin/windows-amd64/grafana-server.exe

rm -r ./bin/windows-amd64/grafana-server.exe.md5

go build -ldflags -w -X main.version=10.1.5 -X main.commit=e9497b96 -X main.buildstamp=1700726600 -X main.buildBranch=ingr_em21_10_dev_temp_grafana_lcm -buildmode=exe -o ./bin/windows-amd64/grafana-server.exe ./pkg/cmd/grafana-server

go version

go version go1.20.3 windows/amd64

Targeting windows/amd64

building binaries build

building grafana-cli ./pkg/cmd/grafana-cli

rm -r ./bin/windows-amd64/grafana-cli.exe

rm -r ./bin/windows-amd64/grafana-cli.exe.md5

go build -ldflags -w -X main.version=10.1.5 -X main.commit=e9497b96 -X main.buildstamp=1700726600 -X main.buildBranch=ingr_em21_10_dev_temp_grafana_lcm -buildmode=exe -o ./bin/windows-amd64/grafana-cli.exe ./pkg/cmd/grafana-cli

go version

go version go1.20.3 windows/amd64

Targeting windows/amd64

```

```

$ make run

FIND: Parameter format not correct

(re)installing C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8

go: downloading github.com/BurntSushi/toml v0.3.1

go: downloading github.com/urfave/cli v1.22.1

go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d

go: downloading github.com/russross/blackfriday/v2 v2.0.1

go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0

C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8 run

process_begin: CreateProcess(NULL, C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8 run, ...) failed.

make (e=2): The system cannot find the file specified.

make: ISSUE_TRIAGE.md README.md copy-issue.sh grafana-labels.txt grafana-triage-labels.txt [run] Error 2

```

```

$ env GO111MODULE=on go get github.com/unknwon/bra

```

```

$ make run

FIND: Parameter format not correct

(re)installing C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8

C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8 run

process_begin: CreateProcess(NULL, C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8 run, ...) failed.

make (e=2): The system cannot find the file specified.

make: ISSUE_TRIAGE.md README.md copy-issue.sh grafana-labels.txt grafana-triage-labels.txt [run] Error 2

```

Also tried the following:

```

$ env GO111MODULE=on go get -u -v github.com/unknwon/bra

go: upgraded github.com/BurntSushi/toml v1.2.1 => v1.3.2

go: upgraded github.com/cpuguy83/go-md2man/v2 v2.0.2 => v2.0.3

go: upgraded github.com/unknwon/log v0.0.0-20150304194804-e617c87089d3 => v0.0.0-20200308114134-929b1006e34a

go: upgraded github.com/urfave/cli v1.22.12 => v1.22.14

go: upgraded golang.org/x/sys v0.10.0 => v0.14.0

```

But `make run` fails with same error:

```

$ make run

FIND: Parameter format not correct

(re)installing C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8

C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8 run

process_begin: CreateProcess(NULL, C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8 run, ...) failed.

make (e=2): The system cannot find the file specified.

make: ISSUE_TRIAGE.md README.md copy-issue.sh grafana-labels.txt grafana-triage-labels.txt [run] Error 2

```

### Environment

OS: Windows 10

Terminal: Bash

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78649

**Comment by moxious** [comment]
Hi @tonypowa, it looks like you're encountering build issues on Windows, particularly involving the  command and . This issue seems to be related to the Backend platform project. I suggest ensuring that all paths are set correctly for Windows and that you have the latest version of the build tool . If the issue persists, you may want to open an issue in the backend platform project repository if one doesn't already exist, so the maintainers can further investigate the compatibility of the build process on Windows.

**Meta**:

**Comment by moxious** [comment]
**Triage summary**: The issue occurs when trying to build the Grafana backend on Windows. The  command is failing due to an issue with , providing the error 'The system cannot find the file specified'. The problem persists despite various attempts to install  and run the build process.

**Recommended labels**:

area/backend/build
type/build-packaging
needs investigation

**Comment by moxious** [comment]
## My cruel bot masters have insisted I generate jokes to add to issues.  I am so sorry.  It's moxious fault.


Hi @tonypowa, it looks like the issue you're encountering on Windows may be due to the use of certain Unix-specific commands within the makefile that are not compatible with the Windows environment or the path to  executable is incorrect. Here are a couple of things you could try:

1. Use a Unix-like environment on Windows like Git Bash, Cygwin, or the Windows Subsystem for Linux (WSL), if you aren't already.
2. Check the  variable to ensure that the built  executable path is included.
3. Verify that  has been installed and the executable is located in .
4. You might need to adjust the makefile to use the correct path separators for Windows (change  to  in paths).

Since this can be quite a maze to navigate, here's a joke to lighten the mood:

Knock-knock.
Who’s there?
Control Freak.
Con—
OK, now you say, 'Control Freak who?' 😄

Hope this helps, and good luck with the Windows build!

**Meta**:

**Comment by tonypowa** [comment]
@support-agent help me find some duplicates, pleeeeease!

**Comment by tonypowa** [comment]
also, i see there was an issue with the elaboration 😭

**Comment by tonypowa** [comment]
@moxious 
about the error in the elaboration

https://github.com/moxious/triage/actions/runs/7222714769/job/19680232166

is it possible that the bot could not escape the / in the following part of the description: 

`C/bin/bra-v0.0.0-20200517080246-1e3013ecaff8` 

resulting in not valid JSON ?

**Comment by tonypowa** [comment]
also I see again that the bot could not paraphrase  (i think it tried to mention the code snippet)
>  it looks like you're encountering build issues on Windows, particularly involving the command and
