### ISSUE TITLE
Alert rule broken in 10.2.2 when using a fixed number as loki query

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#174]
### What happened?

Hi team

In `10.1.x` I use alert rule like this (captured from 10.2.2, but with rule unchanged):

![image](https://github.com/grafana/grafana/assets/15604715/2805cf38-5425-4c05-9807-cbeca868d7a8)

Query B uses a fixed number as query, then I set alert condition like this:

![image](https://github.com/grafana/grafana/assets/15604715/64a70ad6-6c56-4ff8-a9da-effac17d88a8)

By doing this, we can use value D in the alert message like this:

```

Threshold: {{ $values.D }}

Current Value: {{ $values.C }}

```

After upraded to `10.2.x`, this rule is broken with error: 

![image](https://github.com/grafana/grafana/assets/15604715/2ef62365-f3cc-4306-a872-d031c08c4b40)

### What did you expect to happen?

We expect the rule can still work, or find an alternative to define a "variable" for threshold.

### Did this work before?

Yes, it works in 10.1.x.

### How do we reproduce it?

1. Like above pictures, use loki as datasource, add query A as `sum(count_over_time(whatever))`, add query B as `123`. add expressions like picture above.

2. Preview rule.

3. See error.

### Is the bug inside a dashboard panel?

No, it's in unified alerting.

### Environment (with versions)?

Grafana: 10.2.2

OS: whatever

Browser: whatever

### Grafana platform?

Docker

### Datasource(s)?

loki 2.9.2

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#78939

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: After upgrading to Grafana 10.2.2, alert rules that use a fixed number as a query for a Loki datasource no longer work, resulting in an error, although they worked in Grafana 10.1.x.

**Recommended labels**:

area/alerting
type/regression
datasource/Loki

**Comment by moxious** [comment]
Hello @tonypowa,

It appears that you're encountering an issue with the alerting functionality in Grafana. This seems directly related to usage with the Loki datasource and alert rules, which would typically suggest the **Alerting project**.

However, given that you're utilizing a Loki datasource and the issue pertains to a Loki query, it's possible that this may involve integration aspects as well. As such, the **Plugins Platform** team might also be relevant here.

As there is uncertainty regarding the exact scope (alerting logic versus datasource plugin logic) behind this issue and to ensure the appropriate team addresses it, the best fit might be the **Alerting project** where they can verify if the problem is within the core alerting mechanics or if it needs to be redirected to the plugins team.

```markdown
/label ~"Alerting project"
```

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa,

Thank you for bringing this issue to our attention. In order to assist you better, we might need a bit more information. Here are a few clarifying questions and requests:

1. Can you confirm if the problem persists when you create a completely new rule in version `10.2.x` that is equivalent to your existing rule?
2. Could you please provide the complete error message that you are seeing when the alert rule is broken? A detailed error message or stack trace could be very helpful.
3. Is there any relevant log output from Grafana that you can share? This would be particularly helpful if there's more context around the error that is not visible in the UI.
4. Have you attempted any workarounds or steps to resolve the issue on your end since you've encountered it?
5. Could you also include the specific steps to set up the alerting condition or a more detailed reproduction case? For example, include the actual queries or any configuration details that are not visible in the images you've shared.
6. Lastly, the images you've provided seem to be inaccessible. Could you please fix the links or upload the images directly to the issue?

Providing the above information will help us identify the cause of the problem more effectively and ensure that we can suggest an appropriate solution. Thanks for your contribution to the community!

Best,
[Your Name]
