### ISSUE TITLE
Prometheus: Datasource custom query parameters are not applied

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#176]
### What happened?

A Custom Query Parameters specified for Prometheus datasource (from the UI) are not applied during the querying.

### What did you expect to happen?

All queries to the datasource should have custom parameters applied / appended.

### Did this work before?

Not sure, fist time setting this up. 

### How do we reproduce it?

1. Goto Connections > Data sources and add a new one of Type: Prometheus - provide URL and other required details

2. Under section "Other" specify "Custom Query Paramaters"

![image](https://github.com/grafana/grafana/assets/44246099/0cb59773-e55b-423f-8b35-98100374ccc7)

3. Save and Test -> ensure it succeeded.

4. Query that datasource, e.g. `kube_deployment_created{deployment="coredns"}`

5. Confirm that Custom Query Parameters are not applied.

<details>

 <summary>From Query inspector (response omitted)</summary>

```json

{

 "request": {

 "url": "api/ds/query?ds_type=prometheus&requestId=explore_lFK",

 "method": "POST",

 "data": {

 "queries": [

 {

 "refId": "A",

 "expr": "kube_deployment_created{deployment=\"coredns\"}",

 "range": true,

 "instant": false,

 "datasource": {

 "type": "prometheus",

 "uid": "db63c882-fdba-499e-95b1-a9d2239e8f6a"

 },

 "editorMode": "builder",

 "legendFormat": "__auto",

 "useBackend": false,

 "disableTextWrap": false,

 "fullMetaSearch": false,

 "includeNullMetadata": true,

 "exemplar": false,

 "requestId": "undefinedA",

 "utcOffsetSec": -28800,

 "interval": "",

 "datasourceId": 3,

 "intervalMs": 15000,

 "maxDataPoints": 1920

 },

 {

 "refId": "A-Instant",

 "expr": "kube_deployment_created{deployment=\"coredns\"}",

 "range": false,

 "instant": true,

 "datasource": {

 "type": "prometheus",

 "uid": "db63c882-fdba-499e-95b1-a9d2239e8f6a"

 },

 "editorMode": "builder",

 "legendFormat": "__auto",

 "useBackend": false,

 "disableTextWrap": false,

 "fullMetaSearch": false,

 "includeNullMetadata": true,

 "exemplar": false,

 "requestId": "undefinedA",

 "utcOffsetSec": -28800,

 "interval": "",

 "datasourceId": 3,

 "intervalMs": 15000,

 "maxDataPoints": 1920

 }

 ],

 "from": "1701723132499",

 "to": "1701744732500"

 },

 "hideFromInspector": false

 },

...

```

</details>

I tried it with the local Grafana setup (following `contribute/developer-guide.md`) and the custom query params appeared only in one place in the DEBUG logs, with `Sending resource query` action:

```shell

DEBUG[12-04|20:36:31] Sending query logger=tsdb.prometheus endpoint=queryData pluginId=prometheus dsName=prometheus dsUID=bb81d181-99bd-4680-986e-156cf608e758 uname=admin start=2023-12-04T22:36:31.165Z end=2023-12-05T04:36:31.165Z step=15s query="ALERTS{instance=\"prometheus-random-data:8080\"}"

DEBUG[12-04|20:36:31] Sending query logger=tsdb.prometheus endpoint=queryData pluginId=prometheus dsName=prometheus dsUID=bb81d181-99bd-4680-986e-156cf608e758 uname=admin start=2023-12-04T22:36:31.165Z end=2023-12-05T04:36:31.165Z step=15s query="ALERTS{instance=\"prometheus-random-data:8080\"}"

DEBUG[12-04|20:36:31] Using cached permissions logger=accesscontrol.service key=rbac-permissions-1-user-1

DEBUG[12-04|20:36:31] got secret value from cache logger=secrets.kvstore orgId=1 type=datasource namespace=prometheus

WARN [12-04|20:36:31] Could not create user agent logger=plugin.context error="invalid user agent format"

DEBUG[12-04|20:36:31] Sending resource query logger=tsdb.prometheus endpoint=callResource pluginId=prometheus dsName=prometheus dsUID=bb81d181-99bd-4680-986e-156cf608e758 uname=admin URL="api/v1/label/__name__/values?start=1701729360&end=1701751020&tenant_id=my-tenant"

```

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: v10.1.5 (849c612fcb)

OS: MacOS Ventura 13.5

Browser: Chrome (119.x)

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79053

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: Custom Query Parameters specified for a Prometheus datasource are not being appended during querying. The issue is first-time observed, reproduction steps are provided, and debug logs suggest that the parameters are not passed correctly within the query.

**Recommended labels**:

datasource/Prometheus
type/bug
area/backend/plugins
needs investigation

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thanks for providing a detailed explanation of the issue you're facing. To further assist you and ensure our developers can address this effectively, we'd appreciate if you could provide the following additional information:

- When you mention that custom query parameters are not applied, could you clarify if they are missing entirely or incorrect in the final query sent to Prometheus?
- Are there any specific logs or error messages indicating a failure related to these custom query parameters when you execute the query?
- Could you provide the exact value or format of the custom query parameters you are trying to add? This will help us replicate the issue more precisely.
- Since you've found some debug logs, could it be possible to enable more verbose logging and provide any additional logs that might hint at where the custom parameters are being dropped or ignored?
- Can you confirm if you have tried multiple browsers or incognito mode to ensure the issue is not related to browser caching?

This additional information would really help to pinpoint the problem. Once again, thank you for contributing to the project!

**Comment by moxious** [comment]
Hi @tonypowa, it sounds like you are encountering an issue with a data source plugin for Prometheus in Grafana. Given the specifics of your issue, I would recommend this be categorized under the **Plugins Platform** project, as data source plugins are managed in this area. The team responsible for plugins will be best equipped to help troubleshoot and resolve the custom query parameter application issue you've described.

```markdown
/project Plugins Platform
```

To assist the team in addressing your issue more efficiently, consider providing any error messages or logs if available, and confirm that you are using the latest version of the relevant plugins. This information can be crucial for diagnosing and fixing the problem.

**Comment by tonypowa** [comment]
good summary !
incorrect project choice
