### ISSUE TITLE
Explore: LogQL parser misses labels in range aggregations

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#183]
### What happened?

Suppose we have the given LogQL query:

```

quantile_over_time(0.95, {component="foobar"} |= "elapsed_time" | json | unwrap elapsed_time | __error__=""[1m]) by (host)

```

If we enter that query in the code view, it runs fine.

Now click the Builder button to visualize this LogQL in the query builder. It's generally fine, _except_ that it misses the aggregation by `host` label:

![image](https://github.com/grafana/grafana/assets/1280551/323bb0b5-2eef-448a-beb8-3ca31fd3e26e)

### What did you expect to happen?

I expect it to parse out the aggregation by label and represent it in the query builder. It should look like this:

![image](https://github.com/grafana/grafana/assets/1280551/e19fc3dd-3b0f-43a8-aafc-e866605cad00)

### Did this work before?

Don't recall.

### How do we reproduce it?

1. Open Explore view with a Loki data source

2. Enable code view, paste the LogQL example from above.

3. Click Builder

### Is the bug inside a dashboard panel?

No.

### Environment (with versions)?

Grafana: 10.2.2

OS: Linux (Grafana) and Windows (Firefox) 

Browser: Firefox 119

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki v2.9.2

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79194

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
Hello @tonypowa, it seems like this issue might be related to parsing LogQL queries within the Grafana Explore feature, which is designed to build and explore queries for various data sources. This could involve visual representation of queries or issues when switching from code view to the builder. For the best visibility and assistance with the issue, I would recommend associating this issue with the **Explore project**. 

The Explore team specializes in these areas and would be best equipped to address the parsing issue with the query builder.

**Comment by moxious** [comment]
**Triage summary**: In Grafana Explore view, when switching from code view to query builder with a LogQL query that uses range aggregations by labels, the builder is not capturing the 'by' clause (i.e., aggregation by host label). This issue affects Grafana 10.2.2 using Loki v2.9.2 as a datasource.

**Recommended labels**:

area/explore
datasource/Loki
type/bug
area/frontend

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for providing a detailed report of the issue you're facing with LogQL in Grafana. While some parts of the problem are clear, we could use a bit more information to fully understand and address the issue.

1. Could you please confirm if this behavior is consistently reproducible with other queries using range aggregations, or is it specific to the query you've posted?

2. It will be helpful to know if this was working correctly in any previous versions of Grafana that you might have used. In other words, could you indicate if this is a recent regression or has it always been an issue in your experience?

3. When you mention 'it misses the aggregation by `host` label', could you please clarify if the query builder UI does not display the `host` option at all, or if it is displayed but not applied when the query is run?

4. Please include the exact steps to replicate the issue, with more detail if possible. This will help us identify the issue faster. For instance, is there a specific setting in the query builder that may need to be enabled or is a particular pattern in the log data necessary?

5. Can you try this with a different browser and see if the issue persists? This could help determine if it's a browser-specific rendering issue.

6. Since you’ve included screenshots from an expected behavior and the erroneous one, it would also be useful to have the actual image link work to verify the differences. It seems the images are not loading, and you might need to upload the images again or provide a correct path to the assets.

Once you provide these additional details, it will be much easier for the community to pinpoint the exact issue and start working towards a solution. Thank you for your cooperation!

**Comment by tonypowa** [comment]
i would also ask if the issue is specific to explore query editor
i like reading the summary of the issues rather than reading the original issue description!
