### ISSUE TITLE
Excessive memory usage -> grafana crashes

### ISSUE THREAD

**Issue by usmangt** [moxious/triage#187]
### What happened?

Grafana allocates too much memory when uses table panels. This leads to out of memory. 

### What did you expect to happen?

The table will use the new query instead of either letting the existing one run out or terminating the existing one. Or there is much worse memory management.

### Did this work before?

NO

### How do we reproduce it?

1. Create Table 
2. Use a large number of records
3. Click the refresh button as fast as the browser allows.

```
{
 "datasource": {
 "type": "elasticsearch",
 "uid": "vASHHiT7z"
 },
 "fieldConfig": {
 "defaults": {
 "custom": {
 "align": "auto",
 "cellOptions": {
 "type": "auto"
 },
 "inspect": false,
 "filterable": true
 },
 "mappings": [],
 "thresholds": {
 "mode": "absolute",
 "steps": [
 {
 "color": "green",
 "value": null
 },
 {
 "color": "red",
 "value": 80
 }
 ]
 },
 "color": {
 "mode": "thresholds"
 }
 },
 "overrides": [
 {
 "matcher": {
 "id": "byName",
 "options": "attack_type"
 },
 "properties": [
 {
 "id": "custom.width",
 "value": 294
 }
 ]
 },
 {
 "matcher": {
 "id": "byName",
 "options": "geoip.city_name"
 },
 "properties": [
 {
 "id": "custom.width",
 "value": 152
 }
 ]
 }
 ]
 },
 "gridPos": {
 "h": 10,
 "w": 24,
 "x": 0,
 "y": 1
 },
 "id": 26,
 "options": {
 "showHeader": true,
 "cellHeight": "sm",
 "footer": {
 "show": false,
 "reducer": [
 "sum"
 ],
 "countRows": false,
 "fields": ""
 },
 "sortBy": []
 },
 "pluginVersion": "10.1.2",
 "targets": [
 {
 "alias": "",
 "bucketAggs": [],
 "datasource": {
 "type": "elasticsearch",
 "uid": "vASHHiT7z"
 },
 "metrics": [
 {
 "id": "1",
 "settings": {
 "limit": "5000"
 },
 "type": "logs"
 }
 ],
 "query": "host_header: $host_header",
 "refId": "A",
 "timeField": "@timestamp"
 }
 ],
 "title": " ",
 "transformations": [
 {
 "id": "filterFieldsByName",
 "options": {
 "include": {
 "names": [
 "@timestamp",
 "attack_type",
 "geoip.city_name",
 "geoip.country_name",
 "message",
 "policy_name",
 "request",
 "request_status",
 "response_code",
 "severity_label",
 "unit_hostname",
 "uri",
 "violations",
 "vs_name",
 "host_header"
 ]
 }
 }
 },
 {
 "id": "organize",
 "options": {
 "excludeByName": {},
 "indexByName": {
 "@timestamp": 0,
 "attack_type": 2,
 "geoip.city_name": 4,
 "geoip.country_name": 5,
 "host_header": 1,
 "message": 6,
 "policy_name": 7,
 "request": 8,
 "request_status": 3,
 "response_code": 9,
 "severity_label": 10,
 "unit_hostname": 11,
 "uri": 12,
 "violations": 13,
 "vs_name": 14
 },
 "renameByName": {}
 }
 }
 ],
 "type": "table"
}
```

### Environment (with versions)?

Grafana: 10.2.0 to latest (10.2.2).
OS: Windows 10 Enterprise
Browser: MS Edge

### Grafana platform?

I don't know

**Comment by usmangt** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/79203

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: Grafana experiences excessive memory usage and crashes when refreshing table panels with a large number of records from an Elasticsearch datasource. The issue occurs on Windows 10 with MS Edge browser, version 10.2.0 to 10.2.2 of Grafana.

**Recommended labels**:

area/dashboard/panels
type/performance
datasource/Elasticsearch

**Comment by moxious** [comment]
**Elaboration**:


Thank you for providing details about the issue you are experiencing with Grafana. To better assist you, we could use some more information to identify the cause and find a solution. Can you please provide the following additional details? 

- Could you confirm the **exact version of Grafana** you are using when you encounter this issue, as you've mentioned a range from 10.2.0 to 10.2.2?
- **How much memory is being allocated** and what is the **total available memory** on the system where Grafana is running?
- Is this behavior observed with a **specific dashboard or with all dashboards** that include table panels?
- Have you tried monitoring the memory usage over time? It would be helpful to have a **screenshot or graph showing memory usage** that correlates with Grafana crashes.
- Can you provide information about your Elasticsearch datasource, such as the version and resource allocation?
- Are there any **error messages or logs** you can share that occur when Grafana crashes due to excessive memory usage?

By supplying this additional information, we can further analyze the problem and work towards a resolution. Thank you again for reaching out!

**Comment by moxious** [comment]
It appears that you are experiencing performance issues with memory allocation related to the Table Panel in Grafana. This issue may be related to the rendering of large datasets and possibly the way queries are managed in rapid succession. I suggest this issue be categorized under the **Frontend Platform project**, as it deals with the rendering and memory management on the client side within Grafana's frontend framework. The team responsible for the frontend performance and feature implementation would be best suited to address the concern. In the meantime, if practical, consider batching your queries or increasing the refresh interval to avoid overloading the browser memory.
