### ISSUE TITLE
Grafana Alerting: Custom Annotation Variable doesn't get interpreted

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#193]
### What happened?

CASE 1: I created a custom annotation with the following value:

Works:

`{{ $values.B }}`

Works as well:

```

{{ if eq 0 0 }}

 Running

{{ else }}

 Unknown error

{{ end }}

```

The output is displayed in a MS Teams Webhook and looks like:

<img width="412" alt="image" src="https://github.com/grafana/grafana/assets/38406184/4f17e576-931a-4565-b626-c432e4a8c043">

CASE 2: If the custom annotation has the following value, it doesn't work at all:

```

{{ if eq {{ $values.B }} 0 }}

 Running

{{ else }}

 Unknown error

{{ end }}

```

Output in MS Teams channel:

<img width="497" alt="image" src="https://github.com/grafana/grafana/assets/38406184/774ca66d-83e3-45f2-8602-61613b182a18">

The value is displayed in clear-text instead interpreting the code.

I also tried several different approaches for the value:

`{{ if eq values.B 0 }} Running {{ else }} Unknown error {{ end }}`

`{{ if $.values.B.returncode 0 } Running {{ else }} Unknown error {{ end }}`

`{{ if ( $values.B == 0) }} running {{ else if ( $values.B.Value == 1) }}`

The template I use to read the custom annotation:

```

{{ define "alerts_firing" }}



 ISSUE_TRIAGE.md README.md copy-issue.sh grafana-labels.txt grafana-triage-labels.txt **Instanz:** {{ .Labels.instance}}

 ISSUE_TRIAGE.md README.md copy-issue.sh grafana-labels.txt grafana-triage-labels.txt **Returncode:** {{ .Annotations.returncode }}

 ISSUE_TRIAGE.md README.md copy-issue.sh grafana-labels.txt grafana-triage-labels.txt **Returntext:** {{ .Annotations.returntext }}

 ISSUE_TRIAGE.md README.md copy-issue.sh grafana-labels.txt grafana-triage-labels.txt **Grafana:** [Alerting]({{ .Annotations.runbook_url }})



{{ end }}

```

### What did you expect to happen?

I expect the returncode/returntext to be read/interpreted by Grafana as it works with a single value (described in case 1 above).

A list of returncode with corresponding returntext has to be implemented in the value section, hence I have to work with IF ELSE statements:

IF 0 == Running

IF 1 == Parameter Wrong

IF 2 == Service A Not Running

IF 3 == Service B Not Running

IF 4 == Connectivity Issue

etc...

ELSE == Unknown Error

### Did this work before?

Never worked.

### How do we reproduce it?

1. Create MS Teams Webhook (Contact Point)

2. Create Notification templates

3. Create Alert Rule with Custom Annotation

### Is the bug inside a dashboard panel?

Seems to be inside Grafana Alerting:

The error is around reading and interpreting the variable ($values.B) from the alert condition.

<img width="637" alt="image" src="https://github.com/grafana/grafana/assets/38406184/f9a58820-dfc0-44cb-9c38-f149c4891de6">

<img width="676" alt="image" src="https://github.com/grafana/grafana/assets/38406184/bdd5896e-c09c-4ec8-b6ba-fc250f389758">

<img width="720" alt="image" src="https://github.com/grafana/grafana/assets/38406184/ac5bdd57-80b2-4752-a404-53f90367723f">

### Environment (with versions)?

Grafana: 10.0.1 and 10.2.2

OS: Redhat

Browser: Chrome

### Grafana platform?

A downloaded binary

### Datasource(s)?

Elasticsearch

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79299

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
Hello @tonypowa! It looks like you are encountering issues with custom annotation variables in Grafana Alerting. I believe the best team to take a look at this would be the **Alerting project**. They specialize in all aspects of Grafana's alerting features, including notification templates and custom annotations which you're using here.

**Comment by moxious** [comment]
**Triage summary**: The issue involves a bug in Grafana Alerting where custom annotations with conditional logic are not being interpreted correctly when used in a Microsoft Teams webhook. The author expects conditional statements like `{{ if eq {{ $values.B }} 0 }}` to work in a similar way as single value interpolations do, but instead, they are output as plain text.

**Recommended labels**:

area/alerting
type/bug
datasource/Elasticsearch

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reaching out and providing a detailed explanation of the issue you're facing with custom annotations in Grafana Alerting.

Before we proceed, could you please provide a few additional details to help us diagnose the problem more accurately?

1. Can you confirm if the issue persists when using a default template (without custom annotations)? This would help determine if the problem is specific to custom annotations.

2. For CASE 2, you've nested template variables (`{{ if eq {{ $values.B }} 0 }}`). In most templating languages, nesting interpolation syntax like this isn't supported, which might explain why it's rendered as clear-text. Could you try adjusting this to a single templating expression (like `{{ if eq $values.B 0 }}`) and let us know if that works?

3. It'd be helpful to see an example payload from the alert that is being sent to the MS Teams Webhook in both working (CASE 1) and non-working (CASE 2) scenarios. Can you provide the JSON payload that is sent to the webhook?

4. Are there any error messages in Grafana's server logs that could give a hint about what's happening when the problem occurs?

5. Lastly, because GitHub markdown might not accurately represent template syntax, could you share a text snippet or gist containing the raw template you're using, such that we can safely copy-paste and test it?

Once we have this information, we'll be in a much better position to suggest further steps.

Thank you for working with us to resolve this issue!

**Comment by tonypowa** [comment]
really GREAT elaboration!
