### ISSUE TITLE
Dashboards: "Auto Fit" makes page too tall when dashboard contains a variable input

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#195]
### What happened?

Made a dashboard that uses a variable that is shown in the UI, then executing "Auto Fit" (shortcut: d + a), dashboard was resized to be larger than the full height of the visible window canvas

Demo dashboard: https://snapshots.raintank.io/dashboard/snapshot/5BwzIEyYjaLs0Resj6TJQUdTjUSDWELh

### What did you expect to happen?

That the dashboard was resized to exactly fit the visible browser canvas

### Did this work before?

Not that I know of, seems to have been mentioned on the initial implementation issue too: https://github.com/grafana/grafana/issues/12768#issuecomment-877234071

### How do we reproduce it?

1. Create a dashboard with a table, e.g from the test grafana random walk

2. Make the table span the full dashboard height

3. Add a "Text Box" variable in the dashboard and save it

4. Resize the browser window (smaller or larger)

5. Make grafana Auto Fit dashboard (shortcut: d+a)

Observe that the dashboard is resized to be larger than the visible browser view

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana cloud and local grafana version v9.1.6 (92461d8d1e)

OS: Ubuntu 22.04

Browser: Firefox (120.0 (64-bit)) and Chromium Version 120.0.6099.71 (Official Build) snap (64-bit)

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79313

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
**Triage summary**: The 'Auto Fit' feature causes the dashboard to become larger than the browser's visible window when it contains a variable input. It fails to resize itself to fit within the visible canvas area. The issue occurs in both Grafana Cloud and local instances, on Ubuntu 22.04 with Firefox and Chromium browsers.

**Recommended labels**:

area/dashboard
type/bug

**Comment by moxious** [comment]
**Elaboration**:


Thank you for submitting a very clear and detailed issue! Your description of the problem, the steps to reproduce it, and the environment information are very helpful.

Since this seems to be a UI issue, could you please provide a screenshot or screen recording that visualizes the problem after step 5? Sometimes, visual context can help diagnose the problem more efficiently.

Additionally, have you tried clearing your browser cache or using incognito mode to see if the issue persists there?

Finally, it would be beneficial to know if this issue occurs only when a specific type of panel or variable is present in the dashboard (i.e., does it happen with other panels or without the "Text Box" variable?).

These further details can assist us in pinpointing the issue more accurately. Thank you again for your contribution!

**Comment by tonypowa** [comment]
good elaboration!
