### ISSUE TITLE
Dashboard list doesn't update with Custom Variables

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#199]
### What happened?

Changed a custom variable with the Options "yes" and "no".

Dashboard list URL doesn't update.

![Bug](https://github.com/grafana/grafana/assets/59748956/58e340a3-6287-4f13-9bd4-50359f1de3d9)

### What did you expect to happen?

Dashboard list URL updated with new custom variable value

### Did this work before?

Don't know, but with other variables it works.

### How do we reproduce it?

1. Creat Custom Variable and Dashboard list with entrys and allow variables to be included

![Variable](https://github.com/grafana/grafana/assets/59748956/e1bc74dc-b21c-4d0b-a568-2f3e9f6ecb79)

![Dashboard](https://github.com/grafana/grafana/assets/59748956/866f45ed-690f-4193-8039-e20e2559045d)

2. Change Variable and hover over a page to show the URL

### Environment (with versions)?

Grafana: v10.2.2 

OS: Windows 10 Pro

Browser: 120.0 (64-Bit)

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79402

**Comment by moxious** [comment]
@support-agent Do we have similiar issues already?

**Comment by moxious** [comment]
Hi @tonypowa! This issue seems related to the dashboard functionality and how variables are handled in URLs. It might be best associated with the **Frontend Platform project**, as they deal with the user interface and experience. Could you please provide more details about the steps to reproduce this, and confirm that the issue persists on the latest version of Grafana? This information can help the team to investigate the problem more efficiently.

**Comment by moxious** [comment]
**Triage summary**: The dashboard list is not updating the URL as expected when changing a custom variable. The behavior occurs with specified options 'yes' and 'no,' and it is unclear if this functionality worked in previous versions or if it's unique to certain variables.

**Recommended labels**:

area/dashboard
type/bug
needs investigation

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for taking the time to submit this issue. It seems like you're experiencing problems with the dashboard list not updating after changing a custom variable. To help better understand and address the issue, we need a bit more information from you. Here are some additional details that would be helpful:

1. **Reproduction Steps:** You've mentioned steps to reproduce the issue. Could you please confirm that these steps consistently cause the issue you're describing? Also, is there any specific sequence of actions that leads to the problem?

2. **Expected vs Actual Behavior:** You've explained your expected outcome, but can you also provide detailed information about the actual behavior? For instance, does the URL stay completely unchanged, or does it partially update?

3. **Previous Functionality:** You noted that you don't know if this worked before. Have you or someone else in your team been able to use this functionality in the past without facing this issue?

4. **Screenshots and Links:** The screenshots and links to the images seem to be broken, or the paths may be incorrect. Could you please re-upload them or check the paths to ensure they are accessible and provide a clear view of the problem?

5. **Console Errors:** Are there any error messages in the browser console when the issue occurs? These error messages can be crucial in diagnosing the problem. To check for errors, you can right-click the page, select 'Inspect', navigate to the 'Console' tab, and try reproducing the issue.

6. **Network Issues:** Sometimes, issues with URL updates might be related to caching or network problems. Could you please check if there are any network request failures or caching issues by looking at the 'Network' tab in your browser's developer tools?

7. **Datasource Configuration:** While you haven't mentioned any specific datasource, can you confirm if this issue is related to a certain datasource? And if so, could you provide more details on the configuration?

Any additional context or details you can provide will help us triage and resolve this issue. If you have any further information that you think might also be relevant (e.g., logs from Grafana, Docker configurations), please share that as well.

Thank you for participating in the community, we appreciate your contributions!
