### ISSUE TITLE
Dashboards: on mobile, choosing the time range zooms in the window

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#213]
### What happened?

Better show once than describing in text.

1. Open a dashboard on mobile (I use Safari, also tested it on Chrome and got the same behaviour):

![telegram-cloud-photo-size-2-5190566761920057681-y](https://github.com/grafana/grafana/assets/83376337/7c670999-d03b-479e-80d7-0e7c349bbaef)

2. Click the three dots at the top (so far everything's good):

![telegram-cloud-photo-size-2-5190566761920057682-y](https://github.com/grafana/grafana/assets/83376337/f93d3065-82e1-47c1-b4fb-05e5dfd28d07)

3. Choose the time range (notice the page is zoomed in a bit):

![telegram-cloud-photo-size-2-5190566761920057683-y](https://github.com/grafana/grafana/assets/83376337/af06318c-35d4-4db1-9898-c120600bdf35)

4. The time range picker closes, and the page is stayed zoomed in as on step 3:

![telegram-cloud-photo-size-2-5190566761920057684-y](https://github.com/grafana/grafana/assets/83376337/db3d53c6-92ae-4d64-bcfd-57facb27138a)

 

### What did you expect to happen?

Page should not zoom in, as I have to zoom it out every time I need to change a time range and it's quite inconvenient.

### Did this work before?

Not sure to be honest.

### How do we reproduce it?

See steps above.

### Is the bug inside a dashboard panel?

It applies to all the dashboards I have

### Environment (with versions)?

Grafana: latest at the moment

OS: iOS

Browser: Safari (also reproducible on Chrome at least)

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79702

**Comment by moxious** [comment]
**Summary**: The issue describes a problem where the browser window zooms in when selecting a time range on a Grafana dashboard using a mobile browser (Safari/Chrome), and does not zoom back out, requiring manual adjustment each time, which is inconvenient for the user.

**Comment by moxious** [comment]
Hello @tonypowa! Thanks for reporting this issue with the mobile view of dashboards on Grafana.

Based on the description, it seems to be a problem related to the frontend mobile responsive interface of Grafana. Therefore, the appropriate team to handle this would be the `Frontend Platform project` which deals with the overall Grafana user interface, including mobile responsiveness.

```suggestion
May I suggest adding this to the `Frontend Platform project` board for better visibility and potentially quicker resolution?
```

Keep an eye on this issue for updates from the project team.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thanks for reporting the issue with the time range picker on mobile devices. Your initial description and the steps to reproduce are a good start, but we need a bit more information to help troubleshoot this problem effectively. 

Could you please provide the following additional details?
- **Exact version of Grafana** you're using. 'Latest' can often mean different versions, depending on the source or time of download.
- **Device and OS version**: Since mobile behaviors can vary by device and version, knowing the exact model of your device and the OS version could be helpful.
- **Grafana configuration**: Are there any specific configurations you've set up that might alter the behavior of the time range picker? This can include custom styles, scripts, or plugins.
- **Datasource details**: While you've mentioned it's not specific to a dashboard panel, knowing which datasources are in use could reveal if there's a unique interaction happening with certain types of data.

Lastly, reproducing the issue with exact steps is crucial for us. Could you please:
- Confirm that the steps described are complete and there are no additional interactions?
- Provide the configuration of a minimal dashboard (export if possible) where this issue occurs, so we can see if it's reproducible with default settings?

Once we get these details, we'll be in a much better position to understand what’s going on. Thank you for your contribution to the community!
