### ISSUE TITLE
Grafana 10.2.3 Elasticsearch plugin error - An error occurred within the plugin

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#215]
### What happened?

<img width="833" alt="Снимок экрана 2024-01-18 192408" src="https://github.com/grafana/grafana/assets/99013098/9dcef2aa-5fbd-4af2-a8b4-fbd1009241bf">

I recently upgraded Grafana from 10.0.9 to 10.2.3 and I’m observing the following errors for each of my elasticsearch datasources:

message: “An error occurred within the plugin”

messageId: “plugin.downstreamError”

GET https://grafana.dev.leoncorp.net/api/datasources/uid/PE4E1D10B840E7EAC/resources/ 500 (Internal Server Error)

My gitlab datasource config:

name: “Stasaoo_Test”

type: “elasticsearch”

access: “proxy”

url: “My URL”

basicAuth: true

basicAuthUser: “elast”

jsonData:

includeFrozen: false

index: “[myindex-*]YYYY.MM.DD”

interval: “Daily”

timeField: “@timestamp”

maxConcurrentShardRequests: “256”

oauthPassThru: false

sigV4Auth: false

secureJsonData:

basicAuthPassword: “{{ grafana_elasticsearch_password }}”

For all my panels that use elk datasource work, alerting is ok but I’m curious what is the reason for such an error?

### What did you expect to happen?

Test datasource without any errors

### Did this work before?

There was no error in the version 10.0.9

### How do we reproduce it?

1. Each panel (or graph) with ELK datasource shows such error

2. Connections - Data Sources - Your datasource - Test

### Grafana platform?

Other

### Datasource(s)?

esVersion: "7.16.0"

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80838

**Comment by moxious** [comment]
Hi @tonypowa, it appears you're experiencing an error with the Elasticsearch datasource plugin after upgrading to Grafana 10.2.3. Can you provide the plugin version you're using and confirm if any errors are being logged in the Grafana server logs? Additionally, since it seems to be related specifically to the Elasticsearch plugin, I suggest transferring this issue to the **Plugins Platform** project so that the relevant team can further assist you.

**Comment by moxious** [comment]
**Summary**: An issue was opened by tonypowa for Grafana version 10.2.3 where users are encountering an 'An error occurred within the plugin' message with Elasticsearch data sources after upgrading from version 10.0.9. The problem causes a 500 Internal Server Error when test queries are run, despite alerting and panel functionality being operational. The user included configuration details and asked for the reason behind this error.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for reporting the issue with the Elasticsearch plugin in Grafana 10.2.3. To better assist you, we need some additional information that could help us understand the problem more clearly. Here are a few questions and requests for information that would help us investigate further:

1. Could you provide the exact error message returned by Elasticsearch or found in the Grafana server logs? This could contain more details that would help us pinpoint the issue.

2. Since you've mentioned that this issue occurs after upgrading Grafana, it might be helpful to compare the Elasticsearch plugin configurations between the two versions (10.0.9 and 10.2.3). Have you noticed any differences or made any changes during the upgrade that could affect how Grafana interacts with Elasticsearch?

3. Can you confirm whether the Graffana backend or the Elasticsearch data source is behind any proxy, firewall, or other network components that could affect connectivity between the two services?

4. Could you provide more details on the Grafana platform you're using (e.g., Docker, standalone binary, cloud service)? Specific details about the environment setup can sometimes be the key to solving such issues.

5. Are there any other error messages in the browser's console or network tab when you attempt to test the datasource or when you observe the issue on the panels?

6. Have you made any changes to Grafana or Elasticsearch plugins' settings/permissions after the upgrade that might relate to the issue?

7. Lastly, can you provide the Grafana logs entry pertaining to the time when error occurs? This information can be extremely useful for troubleshooting.

Once you've provided this information, we can proceed to diagnose the issue more effectively. Thank you!
