### ISSUE TITLE
RBAC：grafana v10+ rabc permission database design problem

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#218]
### What happened?

The rabc permission database table design of Grafana v10 + has the problem of write amplification. On average, a dashboard data will be written to 10 times the permissions table, causing many slow queries and server returns errors

we have 1000000+ dashboards, therefor the permissions table has millions of data

### What did you expect to happen?

the permissions table need redesign

Mainly need to deal with the design of default permissions, this part of the data can not be written to db

### Did this work before?

yes， dashboard_acl is good

### How do we reproduce it?

1. create a dashboard

2. take look how many data will be written to permissions

### Environment (with versions)?

Grafana: v10

OS: debian

Browser: chrome

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79781

**Comment by moxious** [comment]
**Summary**: The issue reports a problem with RBAC permission database design in Grafana v10+, where a single dashboard write results in an excessive number of permission table entries, leading to slow queries and server errors. The author seeks a redesign for handling default permissions to avoid such write amplification, noting that the previous `dashboard_acl` system did not have this problem.

**Comment by moxious** [comment]
Thank you for bringing up the concern with Grafana v10+ RBAC system. It seems like this issue is primarily concerned with backend database performance related to RBAC handling for a large number of dashboards. This issue might best fit the **Backend Platform Project**, as it deals with core backend functionality and database concerns of Grafana. Please move this issue to that project for further insight and assistance.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reporting this issue with Grafana's RBAC permissions table. In order to better understand the problem and assist you effectively, we need a few more details. Could you please provide the following additional information?

- **Reproduction Steps:** Could you give a more detailed step-by-step procedure of how to reproduce the issue, including specific actions that lead to the slow queries and errors?

- **Error Logs:** Are there any specific error messages, stack traces, or log outputs that occur when the server returns errors? If so, could you please share them?

- **Database Details:** What database are you using for the permissions table? Also, what are the table's schema and indices?

- **Performance Metrics:** You mentioned slow queries – do you have metrics or query performance data that demonstrate the write amplification issue?

- **Configuration Details:** Is there any custom configuration for the RBAC or permissions set up that might be influencing this behavior?

- **Version Details:** Has the write amplification issue started exactly after an upgrade to Grafana v10 or at a different point in time?

- **Comparison with Previous Version:** You mentioned that `dashboard_acl` worked well before. Could you explain how the behaviour and performance differed with the previous implementation?

Providing this information will help us pinpoint the issue more accurately and explore the necessary changes to resolve the write amplification problem. Thank you for your collaboration!
