### ISSUE TITLE
Dashboard List: Search Function Not Working After Enabling Subfolders

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#222]
### What happened?

![image](https://github.com/grafana/grafana/assets/48425373/b328a5ee-6d7f-4fcd-98f6-e53b94ab2199)

I encountered an issue while using the Dashboard List. I attempted to use Tags for searching, with Dashboards selected as my folder and the Subfolders option enabled. However, I found that the search function did not work as expected.

### What did you expect to happen?

Filter out the Dashboards with the tag "class".

Select a single folder works to filter out Dashboards with the tag "class".

### Did this work before?

Disabling Subfolders works

### How do we reproduce it?

1. Enabling Subfolders　

2. Adding tags to the dashboard in Subfolders　

3. Using Dashboard List, filter tags under the Dashboards scope

### Environment (with versions)?

Grafana: 10.2.2

OS: linux

Browser: Chrome 120

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79852

**Comment by moxious** [comment]
**Summary**: An issue has been reported where the search function in the Dashboard List of Grafana 10.2.2 does not work correctly when subfolders are enabled and tags are used for searching.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reaching out and providing information about the issue you're facing with the Dashboard List's search function in Grafana. To help us address the issue more effectively, could you please provide a bit more detail on the following points?

1. Could you confirm if there were any error messages in the browser console or any logs on the Grafana server side when the search fails to work as expected?

2. It would be helpful to understand more about the behavior you are experiencing. When you say the search function did not work, could you elaborate on that? Does it mean the search returns no results, incorrect results, or is there a delay/hang in the functionality?

3. Is it possible for you to share the query or parameters you're using when attempting to filter by tags? This can help in replicating the issue more accurately.

4. Since enabling and disabling subfolders seems to have an impact, could you specify if this feature was working as expected in any previous versions of Grafana?

5. Lastly, in order to replicate the issue in the same environment context, it would be beneficial to know if you're running any plugins or other Grafana features that might be interacting with the Dashboard List.

Once we have this additional information, we will be in a better position to understand and subsequently resolve the issue.

Thank you for your cooperation, and we appreciate your contribution to the community!

**Comment by moxious** [comment]
Hello @tonypowa, thank you for bringing this to our attention. This appears to be an issue related to the core functionality of Grafana dashboards. It would be pertinent to associate this with the **Dashboards Sharing squad project** since it deals with managing and sharing dashboards, including search functionality within the dashboard list. I will ensure the right team sees this so they can look into resolving the search problem with subfolders enabled.
