### ISSUE TITLE
Alert Formatting in Outlook

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#227]
### What happened?

![grafana email outlook](https://github.com/grafana/grafana/assets/34842138/fd8026d5-4d8e-4ac9-b90e-39e598adb83a)

Since the light themed email was introduced in https://github.com/grafana/grafana/pull/72398 the formatting has been incorrect in Microsoft Outlook. It is displaying like this in Outlook 2016 and 2019 (two different systems, on different networks/configurations).

I am not well versed in HTML and CSS, but it appears to me that there are classes being called which don't exist (or I can't find any mention of them in Grafana files or on the internet). These classes have outlook in the name (e.g. border-top-outlook, background-outlook). Is this something inherent in Outlook, or is it just missing?

### What did you expect to happen?

![grafana email firefox](https://github.com/grafana/grafana/assets/34842138/684f4de7-4d47-4b6d-a43b-87baaf71085f)

This is what the same html looks like when opened in a browser.

### Did this work before?

This worked prior to 10.2.0, though the theme changed considerably so it was not formatted the same.

### How do we reproduce it?

1. Install Grafana 10.2.x

2. Create an email contact point

3. Create an alert

4. Open alert email in Microsoft Outlook

### Environment (with versions)?

Grafana: 10.2.0/10.2.2

OS: Microsoft Windows 10

Browser: Mozilla Firefox/Microsoft Edge

Email Client: Microsoft Outlook 2016/2019

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#79898

**Comment by moxious** [comment]
**Summary**: Issue #227 is open, reporting incorrect formatting for light themed emails in Microsoft Outlook 2016 and 2019 following changes introduced in a recent Grafana update, with suspicion that nonexistent CSS classes may be causing the issue.

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you're encountering formatting issues specific to alerting emails in Grafana. This appears to be related to the Alerting project. The team responsible for alerting features might be able to help you diagnose and resolve these email rendering issues within Microsoft Outlook.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reporting the issue with the Grafana alert email formatting in Outlook. It sounds like you might have stumbled upon a styling compatibility problem that's specific to Outlook. We definitely want to help resolve it.

However, the images that you've provided to show the formatting issues seem to be broken links (we aren’t able to see them), and it could be really helpful to have them for a visual understanding of the problem. Also, could you verify that the classes you're mentioning (like `border-top-outlook`, `background-outlook`) are indeed not present in the code? Having snippets of the code where they're referred to might also be useful.

Here are a few additional questions and items that could help us address your issue more efficiently:

- Can you provide the raw HTML of the email that is being generated? This could help identify any discrepancies that might be causing the formatting issues in Outlook. 
- Are there any specific error messages in Outlook that could give us a clue about what's going wrong?
- As you mentioned that the issue occurs in Outlook 2016 and 2019, have you noticed if this issue is also present in the web version of Outlook?

Once you've provided the additional information, we'll be better equipped to help troubleshoot and potentially fix the issue.

Thank you for your contribution!
