### ISSUE TITLE
Transform data: Organize fields by name duplicate columns

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#234]
### What happened?

I have mixed datasource.

![image](https://github.com/grafana/grafana/assets/51740847/e0e7960d-2cab-4b52-bbac-e9e814551980)

since upgrade v10.2.3 (1e84fede543acc892d2a2515187e545eb047f237)

I'm having a problem with the naming columns.

- v10.2.3 (1e84fede543acc892d2a2515187e545eb047f237)

In this image, no more renaming and duplicate columns appear.

![img2](https://github.com/grafana/grafana/assets/51740847/e014b802-936a-4974-a19f-fc6985abc825)

### What did you expect to happen?

- v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)

In this image, you can see that my columns are automatically renamed, which allows me to organise them.

![img1](https://github.com/grafana/grafana/assets/51740847/eac394a7-c5fd-4657-bd11-eac72bb00027)

### Did this work before?

- v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)

In this image, you can see that my columns are automatically renamed, which allows me to organise them.

![img1](https://github.com/grafana/grafana/assets/51740847/eac394a7-c5fd-4657-bd11-eac72bb00027)

### How do we reproduce it?

update grafana

### Environment (with versions)?

Grafana: v10.2.3 (1e84fede543acc892d2a2515187e545eb047f237)

OS: Ubuntu Linux 18.04.6

Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

**Comment by moxious** [comment]
**Summary**: User tonypowa reports an issue after upgrading Grafana to version 10.2.3 where column naming and organization functionality is not working as expected, resulting in duplicated column names that were properly renamed and organized in the previous version 10.2.2.

**Comment by moxious** [comment]
Hello @tonypowa, it looks like this issue is related to the handling of datasource columns after a version upgrade in Grafana. I would suggest this belongs to the **Backend Platform project**, as the changes from version v10.2.2 to v10.2.3 you've mentioned possibly affect the backend's processing of datasource queries and column renaming features. It would be helpful for the backend team to take a look at this.

To get this to the right team, consider adding this to the Backend Platform project for further examination.

Also, if you have not done so already, please ensure that your report follows the guidelines for submitting a bug, including any logs or additional information that could help reproduce and resolve the issue.
