### ISSUE TITLE
Cloudwatch Datasource : Query cross region metrics

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#235]
### What happened?

I connected my monitoring accountA on us-east-1 to my source accountB on us-east-1.

This accountB in fact works on us-east-2. 

I've enabled cross-region metrics so I can see from the `All Metrics` section of Cloudwatch inside my AccountA the metrics from us-east-2 of the AccountB.

But when I try to request this using Cloudwatch datasource inside Grafana and I can only see the metrics from us-east-1.

### What did you expect to happen?

See the metrics from AccountB on us-east-2 using Cloudwatch datasource inside Grafana

### Did this work before?

No

### How do we reproduce it?

1. Have 2 accounts 

2. Create a bucket on accountA on regionA

3. Create another bucket on accountB on regionB

4. Enable cloudwatch cross account cross region monitoring using accountA as monitoring account and accountB as source account.

5. Link accountA to grafana using Cloudwatch data source

6. Try to get metrics from the bucket of accountB

### Environment (with versions)?

Not useful

### Grafana platform?

Kubernetes

### Datasource(s)?

Cloudwatch

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80091

**Comment by moxious** [comment]
**Summary**: User tonypowa reports an issue where cross-region metrics from another AWS account are visible in the AWS Cloudwatch 'All Metrics' section but do not appear when querying via the Cloudwatch datasource in Grafana, despite enabling cross-region metrics.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for taking the time to report this issue and providing the steps to reproduce it. In order to help you more effectively, we need a bit more information about your setup and the problem you're encountering. We appreciate your collaboration to get to the bottom of this issue. Here are some questions and requests to further clarify the situation:

1. Could you confirm that the IAM Roles/Policies attached to your Grafana instance on Kubernetes have the necessary permissions to access CloudWatch metrics across the specified regions?
2. Have you tried querying metrics for any other service using the cross-region set up in CloudWatch from the same Grafana datasource? If so, was this successful?
3. Are there any error messages displayed in the Grafana logs or on the dashboard when you attempt to query the metrics for accountB in us-east-2?
4. It could be useful to share the configuration of the CloudWatch datasource in Grafana while hiding any sensitive information.
5. Since environment details can sometimes play a critical role, could you specify which versions of Grafana and the CloudWatch data source plugin you are using?
6. A screenshot of the issue, showing the failed queries in the Grafana dashboard, may provide visual clues to help us understand the problem better.

By providing this additional information, we'll be in a better position to diagnose the problem and suggest a possible solution. Thanks again for your cooperation!

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you're facing issues with cross-region metrics queries in Grafana using the Cloudwatch datasource. This issue appears to be related to AWS data sources in Grafana. Thus, I am tagging this issue for the **AWS Datasources project** team's attention. They are best equipped to address complexities with AWS services integration within Grafana.

```json
{"projects":["AWS Datasources project"]}
```

By providing the reproducible steps, you've made it easier for the team to understand and investigate the issue. They'll be able to determine if it's a limitation, a bug, or a potential enhancement. Thank you for the report!
