### ISSUE TITLE
Snapshots: values are connected despite `Connect null values` set to `never`

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#236]
### What happened?

I have a dashboard from performance tests, with each test separated by a quiet period. The dashboard sets `Connect null values` to `never` and that works as expected, for example here are the results of 6 different tests:

<img width="687" alt="Screenshot 2024-01-09 at 13 00 04" src="https://github.com/grafana/grafana/assets/9566114/90f67125-c6ec-4de8-9c39-d4af1eaff0c2">

However, when I export a snapshot of this dashboards, values are connected, making the dashboard much less readable:

<img width="433" alt="Screenshot 2024-01-09 at 13 02 36" src="https://github.com/grafana/grafana/assets/9566114/9839e4b4-ec06-4a2c-b1c1-922121e76d11">

### What did you expect to happen?

I'd like the snapshot to look just like the dashboard

### Did this work before?

Don't know.

### How do we reproduce it?

1. Create a dashboard with some "gaps" (null values)

2. Set `Connect null values` to `never`

3. Publish a snapshot

A sample snapshot with the issue:

https://snapshots.raintank.io/dashboard/snapshot/WVtYt4of7WCUm2Oy114StXUhieI8jLAZ?orgId=2

### Environment (with versions)?

Grafana: v10.2.2 (161e3cac5075540918e3a39004f2364ad104d5bb)

OS: Linux

Browser: Chrome/macOS

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80211

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa 👋, 

Thank you for providing detailed information about the snapshot issue you're encountering. To better assist you and identify the root cause, I have a couple of follow-up questions:

1. Can you confirm if there were any changes to the dashboard settings between observing the correct behavior and taking the snapshot?
2. Have you tried creating a new snapshot after setting `Connect null values` to `never` to see if the problem persists across multiple snapshots?
3. Are there any console errors in your browser's developer tools when viewing the snapshot?
4. Could you please provide the JSON model of the dashboard panel that is experiencing this issue? This could help us replicate the problem more accurately.
5. Additional information about your environment, such as the version of Prometheus or any specific visualization plugins being used, might also be relevant.

We aim to reproduce the issue precisely to suggest a fix or escalate it to the development team accordingly. I'll be waiting for your response!

Thanks again for bringing this matter to our attention!

**Comment by moxious** [comment]
**Summary**: Issue #236 is still open, where user tonypowa reports that when exporting a snapshot from a Grafana dashboard with 'Connect null values' set to 'never', the null values are incorrectly connected, resulting in a less readable snapshot. The expected behavior is for the snapshot to look identical to the actual dashboard settings.

**Comment by moxious** [comment]
Hi @tonypowa, thanks for bringing this up. This issue seems related to how snapshots handle visualization settings in Grafana. It might be a bug within the **Dashboard Sharing squad**, which is focused on features like sharing and snapshots. I'll label this issue for their attention so that the right team can look into it.
