### ISSUE TITLE
Ha-test-unified Alerting: Unsupported config option for services.db: 'platform'

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#238]
### What happened?

ha-test-unified-alerting setup did come up

### What did you expect to happen?

I expected the docker-compose up to bring up all the containers

### Did this work before?

NA

### How do we reproduce it?

1. Clone main branch

2. Create docker image from make build-docker-full

3. Run docker-compose up -d from `grafana/devenv/docker/ha-test-unified-alerting`

The logs of grafana1_1 gives this error

```

grafana1_1 | logger=settings t=2024-01-09T14:35:41.366759927Z level=info msg="Path Plugins" path=/var/lib/grafana/plugins

grafana1_1 | logger=settings t=2024-01-09T14:35:41.366764678Z level=info msg="Path Provisioning" path=/etc/grafana/provisioning

grafana1_1 | logger=settings t=2024-01-09T14:35:41.366769416Z level=info msg="App mode production"

grafana1_1 | logger=sqlstore t=2024-01-09T14:35:41.367277595Z level=info msg="Connecting to DB" dbtype=mysql

grafana1_1 | logger=migrator t=2024-01-09T14:35:41.3718039Z level=info msg="Starting DB migrations"

grafana1_1 | logger=migrator t=2024-01-09T14:35:41.391715125Z level=info msg="migrations completed" performed=0 skipped=517 duration=1.072415ms

grafana1_1 | logger=secrets t=2024-01-09T14:35:41.398913731Z level=info msg="Envelope encryption state" enabled=true currentprovider=secretKey.v1

grafana1_1 | logger=local.finder t=2024-01-09T14:35:41.457209882Z level=warn msg="Skipping finding plugins as directory does not exist" path=/usr/share/grafana/plugins-bundled

grafana1_1 | logger=query_data t=2024-01-09T14:35:41.460194686Z level=info msg="Query Service initialization"

grafana1_1 | logger=live.push_http t=2024-01-09T14:35:41.462316244Z level=info msg="Live Push Gateway initialization"

grafana1_1 | logger=ngalert.multiorg.alertmanager component=clustering t=2024-01-09T14:35:56.87756291Z level=info msg="setting advertise address explicitly" addr=172.21.0.6 port=9094

grafana1_1 | Error: ✗ failed to initialize alerting because multiorg alertmanager manager failed to warm up: context deadline exceeded

grafana1_1 | logger=ngalert.multiorg.alertmanager component=clustering t=2024-01-09T14:36:20.893608833Z level=info msg="Waiting for gossip to settle..." interval=2s

```

### Environment (with versions)?

Grafana: 10.2.1

OS: Ubuntu

Browser:

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80223

**Comment by moxious** [comment]
**Summary**: The issue is with the 'ha-test-unified-alerting' setup, where running 'docker-compose up' does not bring up all containers, leading to an error in 'grafana1_1' about failing initialization of alerting due to 'multiorg alertmanager manager' not warming up.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for providing details on the issue you're experiencing with setting up ha-test-unified-alerting in Grafana. In order to help you more effectively, we might need a few more details. Could you please provide the following information if possible:

- The exact version of Docker and docker-compose you are using.
- The contents of your `docker-compose.yml` file to make sure there's no misconfiguration, especially surrounding the 'platform' option error mentioned in the title.
- Confirm whether the `services.db` configuration is customized or if you're using defaults.
- The step at which the process fails (is the error immediate, or does it occur after a certain step in the logs?).
- Whether other services in the `docker-compose` file are starting correctly or if they are all encountering issues.
- Full error logs, if the snippet provided in the issue is not complete.

Optionally, could you also:

- Try clearing your Docker volumes with `docker-compose down -v` and see if starting fresh helps?
- Verify the network configurations are correct and that there are no conflicts that might prevent containers from communicating.

A complete diagnostic output or steps to reproduce with a minimal setup might also help isolate the problem.

Looking forward to your response to address the issue effectively!

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you're facing an issue with Grafana's unified alerting in a Docker environment. This issue might be relevant to the team working on the **Alerting project** within the Grafana ecosystem. They can provide more assistance in troubleshooting your problem with the Grafana alerting setup and Docker-compose configurations.
