### ISSUE TITLE
Grafana 10.1.2 Alert Routing Bug

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#245]
### What happened?

Tried creating an alert and labels to route to a team. Tested route. Goes to default notification policy:

![image](https://github.com/grafana/grafana/assets/120418829/57c6a241-317c-4fa2-aa52-882ef8d0b7f5)

![image](https://github.com/grafana/grafana/assets/120418829/0be9d127-cd90-4387-b7b8-06ad16ef862d)

![image](https://github.com/grafana/grafana/assets/120418829/1bb1f9f7-e786-4194-901f-c7f0a1b3d8b7)

This behavior has repeated on three different instances of Grafana 10.1.2 OSS

### What did you expect to happen?

Route to the correct notification policy

### Did this work before?

In 10.0.1 it works

### How do we reproduce it?

1. Create contact point

2. Create notification policy

3. Add labels to alert

4. Click Preview Routing

### Environment (with versions)?

Grafana: 10.1.2

OS: Red Hat Enterprise Linux release 8.8

Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

Any

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue regarding alert routing in Grafana 10.1.2. To help our developers diagnose and resolve this issue, we need a bit more information. Would you be able to provide the following details? This will help us better understand the problem and work on a potential fix more efficiently.

1. **Configuration Details**: Could you share the relevant sections of your configuration files (without any sensitive information) that detail how alerts and notification policies are set up?

2. **Logs**: Are there any logs available when you try to preview the routing or when an alert is triggered? Logs often contain errors or other information that could indicate what might be going wrong.

3. **Screenshots**: It seems that the links to the screenshots you have provided are broken. Would you be able to repost or re-upload the images to ensure we can see the exact issue you're encountering?

4. **Reproducibility**: You mentioned that this behavior repeated on three different instances. Are these instances configured identically? If there are differences, knowing those could be helpful.

5. **Notification Policies**: How many notification policies do you have, and how are they differentiated? Are the labels applied to the alerts exactly matching the labels defined in the notification policies?

6. **Steps Leading to the Issue**: Is there any notable interaction or sequence of actions leading up to the issue, aside from the steps provided to reproduce it?

7. **Regression**: Since you've noted that this was not an issue in version 10.0.1, are there any other changes or upgrades between 10.0.1 and 10.1.2 that took place which could have had an impact?

Once you provide this additional information, it'll be easier for the community and maintainers to dive into the problem and propose a solution. Thank you for your contributions to the open source community and for your cooperation!
