### ISSUE TITLE
Explore: Screen is flickering when moving mouse on loki logs on firefox

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#246]
### What happened?

When I move mouse on loki logs almost whole page flicker (The part with Run Query, Live buttons to the bottom).

I don't have this problem when I use chrome or Vivaldi browser.

### What did you expect to happen?

Page should not flicker/refresh? when I move mouse.

### Did this work before?

I think it worked well in older version of grafana but unfortunatelly i dont have numbers to tell.

### How do we reproduce it?

1. Open grafana loki logs explorer(use firefox)

2. Move mouse over the log records. It should flicker.

### Environment (with versions)?

Grafana: v10.2.2 

OS: Ubuntu 22.04.3 LTS

Browser: Firefox 121.0.1

### Grafana platform?

I don't know

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80455

**Comment by moxious** [comment]
Hi @tonypowa, thanks for reporting this issue. It seems related to Grafana's user interface while interacting with Loki logs, which suggests it would be best handled by the **Explore project** team who are responsible for issues regarding the exploration interface for logs, metrics, and traces. 

To assist the team in resolving your issue, could you please check if there are any console errors in your browser when the flicker occurs and provide that information? It would greatly aid in the troubleshooting process.

Meanwhile, tagging this for the Explore project team's attention: `/explore-project`

**Comment by moxious** [comment]
**Elaboration**:


### Thank you for the detailed report, @tonypowa!
It sounds like you're experiencing an issue with Grafana's UI in Firefox, and this information is helpful for starting an investigation.

However, to dig deeper into this problem, we could use a bit more context:

1. Could you provide any **console logs** that are output in Firefox's developer tools when the flickering occurs?
2. Does the problem persist if you **disable all extensions** in Firefox or try it in Firefox's **Safe Mode**?
3. Is it possible to **record a short video** or **gif** that captures the flickering issue?
4. Are you able to **inspect the element** where the flickering occurs and provide any **HTML/CSS** clues that could be related to the issue?
5. You mentioned that the problem appears in the latest version, but what is the **last version of Grafana where this issue was not present**? Any information on the versions that do not have this problem could be very useful.
6. Lastly, could you clarify what you mean by **Grafana platform**? This would typically refer to whether you're running Grafana on-premises, on Grafana cloud, or in another environment.

Any additional details you provide can help us troubleshoot and resolve this issue more effectively. Looking forward to your response!

**Comment by moxious** [comment]
**Summary**: The issue reports a screen flickering problem on Grafana when moving the mouse over loki logs in Firefox, which does not occur in Chrome or Vivaldi.
