### ISSUE TITLE
After update to 10.2 issues with dynamic variables

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#252]
### What happened?

Hello,

We are doing this:

SELECT

 non_negative_derivative(mean("in_octets"), 1s)*8/1000/1000 / mean("/interfaces/interface/state/high_speed")

FROM

 "autogen"."gnmi_ifcounters"

WHERE

 "acro_reg"::tag =~ /^$Region$/

 AND "acro_dc"::tag =~ /^$DC$/

 AND "acro_cat"::tag =~ /^$Category$/

 AND "acro_provider"::tag =~ /^$Provider$/

 **AND "acro_ifcomplete"::tag =~ /^$Interface$/**

 AND $timeFilter

GROUP BY

 time($Resolution)

 ,"acro_ifcomplete"::tag

Variable 

interface = SHOW TAG VALUES FROM "gnmi_ifcounters" WITH KEY = "acro_ifcomplete" WHERE acro_reg =~ /$Region/ and acro_dc =~ /$DC/ and acro_cat =~ /$Category/ and acro_provider =~ /$Provider/

For the interface names with "/" we see that it's not processing it correctly anymore

For Example:

ams1-rt-01 et-0/1/0 (PF)

Appears as(please see screenshot, since this web page is replacing special characters &#x2 with the proper "/" symbols): 

ams1-rt-01 et-0&#x2F;1&#x2F;0 (PF)

And it throughs an error 

Status: 500. Message: InfluxDB returned error: error parsing query: found 1, expected ; at line 10, char 51

Thus no information is shown on the graphs

<img width="1496" alt="Screenshot 2024-01-17 at 10 30 45" src="https://github.com/grafana/grafana/assets/33316295/891671a9-eb8f-4507-8400-0f1c07f9d163">

### What did you expect to happen?

I would expect for the above query to continue to work

### Did this work before?

yes in version 10.1.6 it still works as expected(no special characters are added in the name)

### How do we reproduce it?

1. Have / in the name and use the query with the dynamic variable as per my example above

### Environment (with versions)?

Grafana: 10.2.3

OS: Rocky 9

Browser: All

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80758

**Comment by moxious** [comment]
**Summary**: The issue, opened by tonypowa, describes a bug introduced in Grafana 10.2.3 where dynamic variables containing slashes ('/') in interface names are not processed correctly, leading to errors and issues displaying graphs. This behavior did not occur in the previous version 10.1.6.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa,

Thank you for the detailed report! It seems like there's an issue with how special characters are handled in interface names after the update. To better understand the problem and find a resolution, could you please provide a little more information?

1. Could you confirm that the REGEX in the query is formatted correctly for the updated version? Sometimes updates change how special characters need to be escaped.

2. Is there a stack trace or more detailed error message available from the Grafana or InfluxDB logs when the error occurs?

3. Have you noticed if the issue occurs only when using dynamic variables or also with static text in the place of variables?

4. Could you provide the actual screenshot showing the issue? It appears the link to the screenshot you've provided is not accessible. You might need to upload the image directly to the GitHub issue again.

5. Could you provide an export of the dashboard panel JSON that includes the problematic query so that we can try to replicate the issue?

Your cooperation will be invaluable in debugging and resolving the issue effectively.

Thanks!
