### ISSUE TITLE
Dashboards: auto refresh not loaded correctly

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#263]
### What happened?

Opening dashboard with set `refresh=auto` fails to properly load this value and fallbacks into disabled refresh.

### What did you expect to happen?

Dashboard will open correctly with previously-saved value `refresh=auto`.

### Did this work before?

Tried on versions 10.2.2 and 10.2.3 (latest) - both not working properly

### How do we reproduce it?

1. Create dashboard

2. Set "Refresh Interval" in top-right corner to "Auto". Grafana automatically assigns refresh interval nicely.

3. Get happy because you don't need to deal with this anymore and try to save your greatest dashboard :)

 You see this so you are even more happy, because it gets saved:

 

 <img width="377" alt="Screenshot 2024-01-18 at 21 29 40" src="https://github.com/grafana/grafana/assets/783794/e71ccce4-c2e0-4b6e-a4e0-255f83b871e9">

 

4. Go to other page in Grafana and try to load your dashboard again. Be sad, because your saved refresh config is not there anymore, refresh is disabled and you have to set it to auto everytime you enter your dashboard :(

### Environment (with versions)?

Grafana: 10.2.2, 10.2.3

OS: macOS Sonoma 14.2.1

Browser: Firefox 121.0

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus (from Mimir), Loki

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#80842

**Comment by moxious** [comment]
**Summary**: The GitHub issue reports that the dashboard auto-refresh feature in Grafana is not remembering the 'auto' setting after being saved. When the dashboard is reopened, the auto-refresh is disabled, requiring the user to set it again manually. This issue persists in Grafana versions 10.2.2 and 10.2.3.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for the detailed report! To better assist you, I'd like to ask a few clarifying questions and request some additional information to help our team diagnose the issue more effectively:

- Can you confirm if this issue occurs consistently every time you save a dashboard with `refresh=auto` and then navigate away, or if it happens intermittently?
- Could you please provide us with the browser's console logs when you save the dashboard and when you load it again? This could give us some insights if there are errors or warnings that might be related to the issue.
- Have you tested this behavior in other browsers as well (e.g., Chrome, Safari)? If so, does the issue persist across different browsers or is it isolated to Firefox 121.0?
- Since you are using Kubernetes, could you check if there are any relevant logs from the Grafana container when the dashboard is reloaded that might indicate an error or misconfiguration?
- Lastly, it would be helpful if you could share the exact JSON configuration of the dashboard that is exhibiting this issue. You can export it from Grafana and remove any sensitive information before sharing.

Once we have this additional information, we'll be in a better position to troubleshoot the issue. Thanks again for contributing to the community!

**Comment by moxious** [comment]
Hi @tonypowa, 

It seems like you're experiencing an issue with dashboard settings not being correctly applied. This might relate to how dashboard configurations are managed and saved. The Dashboards Sharing squad is likely the appropriate team to handle dashboard-related functionality within Grafana. I'll tag this issue for their attention.

```json
{
 "project_name": "Dashboards Sharing squad",
 "issue_number": 263
}
```

Thank you for providing detailed steps to reproduce and the environment info. That will greatly assist in diagnosing the issue.

/cc @DashboardsSharingSquad
