### ISSUE TITLE
Postgres Plugin generates msg="Failed connecting to Postgres" err="invalid option: \"Files\\\\\\\\GrafanaLabs\\\\\

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#267]
### What happened?

Connecting to postgres DB in azure fails with

msg="Failed connecting to Postgres" err="invalid option: \"Files\\\\\\\\GrafanaLabs\\\\\\\\grafana\\\\\\\\data\\\\\\\\tls\\\\\\\\f44631f5-68c8-4cdb-99ba-83321f7ef406generatedTLSCerts\\\\\\\\root.crt'\""

I am not providing a root CA as its set to require and didnt think i needed one but even if i provide one it doesnt work.

The problem seems to be that grafana is installed in the standard installation lcoation in windows C:\program files which has a space in. When i configure certificate content it creates a file here tlsRootCert="C:\Program Files\GrafanaLabs\grafana\data\tls\f44631f5-68c8-4cdb-99ba-XXXXXXXXgeneratedTLSCerts\root.crt" but clearly when using that as the connection string it fails on the space between program files. No idea how to sovle this seems like this is a bug that can only be solved in correcting the code to deal with spaces in paths when using certificate content

Confirmed - when i create a folder and use file path without a space it works. So the issue is that using certificate content creates a cert in a location with a space and doesnt handle quoting it.

### What did you expect to happen?

Connect

### Did this work before?

No

### How do we reproduce it?

1. Create db in azure

2. connect

3.

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

A downloaded binary

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81008

**Comment by moxious** [comment]
Hi @tonypowa, it sounds like you're encountering path issues with the Postgres plugin due to spaces in the Windows file path. This looks like it could be relevant to the **Plugins Platform** project, which handles the plugin development and issues related to them. Meanwhile, as a temporary workaround, you might consider using a directory without spaces or possibly using a symlink to bypass the problem with spaces in the file path.

I'm tagging this for the Plugins Platform team to review the issue with handling spaces in file paths for certificates on Windows installations.

**Comment by moxious** [comment]
**Summary**: The issue #267, opened by tonypowa, describes a problem where the Postgres plugin for Grafana fails to connect to a Postgres database on Azure due to an invalid option error caused by a file path with a space in it. The error occurs when the plugin tries to handle a certificate stored in the default Windows installation path for Grafana, which contains a space. The user confirmed that using a file path without a space resolved the issue

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue you've encountered with the Postgres plugin in Grafana. It seems like the problem is related to file paths with spaces in Windows. To better assist you and facilitate a resolution, could you please provide us with some additional information? Here are a few questions and requests to clarify your issue further: 

1. Can you provide the version of Grafana you're using?
2. What version of the Postgres database are you connecting to?
3. Can you provide the steps you're taking when configuring the connection to the Postgres database within Grafana? This would be very helpful for us to try and reproduce the issue.
4. Is there any additional log output or error messages that could help us understand the problem better?
5. Could you please provide a screenshot or a more detailed description of the configuration settings you are using? Please make sure to blur out or remove any sensitive information.

You mentioned that it works when the filepath doesn't contain a space. As a temporary workaround, have you tried enclosing the path in double quotes in your configuration, or escaping the space with a backslash (e.g., `C:\Program\ Files\`)?

Once we have this information, we'll be better equipped to help address the issue or identify the bug. Thank you for contributing to making Grafana better!
