### ISSUE TITLE
Alerting: Text in the email is not bolded when should be

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#271]
### What happened?

When I used \*\*bold** to make text bold, text in email is not bold. 

![image](https://github.com/grafana/grafana/assets/28779692/0f703326-b7f6-403e-a176-5026d8d75a33)

![image](https://github.com/grafana/grafana/assets/28779692/1cba3ee0-2b57-4f07-ac77-32ae80becd0c)

### What did you expect to happen?

In documentation, it is specified that in notification template we can [format text in bold and italic, and add or remove line breaks.](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/template-notifications/). So I would expect that when I use \*\*bold** to make text bold that text in email will be bold.

### Did this work before?

Didn't use it before.

### How do we reproduce it?

1. Create notification template with \*\*bold** text

2. Send testing email on contact point that has specified this template.

### Environment (with versions)?

Grafana: 10.2.2

OS: 

Browser: 

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81131

**Comment by moxious** [comment]
**Summary**: The issue is about bold formatting not working as expected in Grafana's alert email notifications. Despite the documentation stating that bold and italic formatting should be possible in notification templates, when the author uses markdown syntax for bold, it doesn't reflect in the sent email.

**Comment by moxious** [comment]
Hi @tonypowa! Thanks for reporting this. Based on the details you've provided, it appears that this issue may be related to the Alerting functionalities in Grafana. I'm going to label this for the **Alerting project** so that the team responsible for alert notifications can take a look and help resolve the formatting issue with bold text in emails. Meanwhile, if you have any additional details or steps that could help reproduce the issue, please feel free to add them to this thread.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue! To address it more effectively, we need a bit of additional information. Could you please provide the following details? 

1. Could you confirm if the issue persists with different email clients or is it specific to one? If specific, please let us know which email client you are using. 
2. Are there any relevant logs from Grafana when sending the email that might indicate an error in parsing the markdown? 
3. It's possible that email styling may be overridden by an email client's settings/limitations. Have you tested this with basic markdown (outside of Grafana) in the same email client, and do other markdown stylings work correctly? 
4. Please provide the full content of the notification template you're using, masking any sensitive information. 
5. Can you also try using a backslash before the asterisks (like `\*\*bold\*\*`) to see if it makes a difference? 

Seeing the actual markdown text and knowing a bit more about the environment can help us troubleshoot this further. Providing these details will help us understand the problem better and find a solution more quickly. 

Thank you!
