### ISSUE TITLE
Grafana: When Running Multiple Grafana Pods It's Getting - failure: contact points: could not find object using provided id and hash

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#273]
### What happened?

When running multiple Grafana pods I keep getting the following error:

 "failure: contact points: could not find object using provided id and hash"

 It causes the pod to restart multiple times.

### What did you expect to happen?

I expected Grafana to spin up without any issues

### Did this work before?

No

### How do we reproduce it?

1. Use contact points and run Grafana in HA mode inside K8S

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.1.2

OS: amazon-eks-node-1.27-v20240117

Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Loki

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81139

**Comment by moxious** [comment]
**Summary**: Issue #273 is OPEN, where a user named tonypowa reports that running multiple Grafana pods in Kubernetes results in pods restarting due to a failure to find objects using provided ids and hashes. The user expects Grafana pods to spin up without issues, and details the issue occurring in an Amazon EKS environment using the Loki datasource.

**Comment by moxious** [comment]
Hello @tonypowa, it seems like your issue might be related to running Grafana in a high-availability (HA) setup on Kubernetes, which could be connected to the Grafana Operator or Backend platform. However, your issue appears more infrastructural and might be best handled by the **Grafana Operator Experience Squad** which deals with Kubernetes-related Grafana deployments. I recommend that you transfer this issue to that project for the appropriate support.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting this issue. In order to better assist you, we need a bit more information to properly diagnose the problem and offer an appropriate solution. Could you please provide the following additional details?

- Can you share the configuration file for Grafana (without any sensitive data), specifically highlighting how the HA (High Availability) mode is set up?
- Are there any specific steps you follow when you 'use contact points', as mentioned in your reproduction steps? Please elaborate on this process.
- Have you observed any patterns regarding when the error occurs, such as during scaling events, configuration changes, or network issues?
- Are there any logs from the Grafana pods that might provide more insight into the root cause of the error?
- Do all the Grafana pods experience this issue, or does it only affect some of them?
- Could you verify whether the underlying database used by Grafana for storing dashboards and settings (e.g., SQLite, MySQL, or Postgres) is set up correctly for HA use?

Additionally, any relevant StackTrace or more details of the failure message could be very helpful.

Please attach this additional information so we can proceed to accurately diagnose and resolve this issue. Thank you for contributing to the community!
