### ISSUE TITLE
The Time columns using $__timeGroup are grouped according to UTC time boundaries. 1 hour late compared to Europe/Berlin localtime.

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#276]
### What happened?

- Grafana connected to MySQL DB.

- The time column of all data are saved in UTC in database.

- Grafana server and MySQL server all running in cloud server of ubuntu with default timezone Europe/Berlin +1.0:00. 

The plot is shifted 1 hour before local time (Europe/Berlin) after applied `$__timeGroup`:

<img width="1693" alt="Screenshot 2024-01-24 at 20 27 49" src="https://github.com/grafana/grafana/assets/66997911/6cbeb9ce-3d39-46c1-9cb4-d725ebfc4978">

If directly query the date from database, it shows right time which matches local time.

Table A: with `$__timeGroup` 1min interval.

Table B: directly query datetime from DB.

<img width="212" alt="Screenshot 2024-01-24 at 20 25 30" src="https://github.com/grafana/grafana/assets/66997911/6e492464-3e5c-49fa-9a00-372d294ff49f">

Table A query:

`SELECT

 $__timeGroup(date, 1m) as time_sec,

 COUNT(event) as "event_count",

 event as metric

FROM event_db.event_table

WHERE $__timeFilter(date) and event = "some_event_name"

GROUP BY 1, event

ORDER BY 1

`

Table B query:

`

SELECT date as time_sec FROM event_db.event_table ORDER BY date DESC

`

### What did you expect to happen?

the plot is not shifted and matches the browser time.

temporary solution: add +3600 after `date` 

### Did this work before?

no

### How do we reproduce it?

1. connect a Grafana with Mysql

2. group a datetime column and show the counts of another column

3. see plots

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: V10.2.3

OS: mac os

Browser: Chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

MySQL 10.5.21

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81207

**Comment by moxious** [comment]
**Summary**: Issue #276 reports that when using the $__timeGroup feature in Grafana with a MySQL data source, data plotted is shifted 1 hour earlier than the local time (Europe/Berlin). It is implied this behavior does not match the expected local time display and happens even when the servers are set to the Europe/Berlin timezone.

**Comment by moxious** [comment]
Hello @tonypowa,

Thank you for bringing this to our attention. It seems that you are facing a timezone conversion issue within Grafana dashboards when using the `$__timeGroup` macro with MySQL datasource. This issue may belong to the **Grafana Metrics project** as it relates to time series data handling and visualization features within Grafana. However, since it's also closely tied to datasource query generation and interpretation, the **AWS Datasources project** team, which by the name could also be responsible for generic datasource implementations, may be well suited to address this issue. To ensure this issue gets to the right team, please provide additional details or any configurations related to time settings in Grafana and your MySQL datasource.

Best,
Your GitHub Assistant

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa,

Thank you for reporting this issue. Your detailed environment description and the queries you provided are helpful, but we still need a little more information to understand the root cause and find a solution. Could you please provide the following details?

- Can you confirm that the time zone settings in Grafana's data source configuration are correctly set to `Europe/Berlin` or to use the default browser time zone?

- Are you using any time zone related settings in MySQL that might affect the returned data?

- When you mention adding `+3600 after date` as a temporary solution, can you elaborate on where exactly you're adding this and if you're doing this in the Grafana query editor or somewhere within the database query directly?

- It would be helpful if you could provide an example of the data returned by the `Table B query` (please ensure that any sensitive information is anonymized).

- Additionally, could you share the results of `SHOW VARIABLES LIKE '%time_zone%';` executed in your MySQL server? This would help us understand if the MySQL time zone settings could be affecting the results.

- If applicable, screenshots or additional visual context about the misalignment of the data points in the Grafana panel might be beneficial.

We want to ensure that we address your issue promptly and accurately. Your cooperation in providing this additional information would be greatly appreciated!

Best regards,
The Grafana Team
