### ISSUE TITLE
Graph widget : Y-axis showing same number

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#277]
### What happened?

It is an intermittent issue. On y-axis in the graph widget I see same number at all the scale.

Screenshot attached.

![image](https://github.com/grafana/grafana/assets/18478858/016c83fc-807b-4ef8-a877-e22f5226b392)

### What did you expect to happen?

On y-axis as we go up number should increase.

### Did this work before?

yes.

### How do we reproduce it?

Try creating widget having graphs.

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81222

**Comment by moxious** [comment]
**Summary**: Issue #277 remains open and describes an intermittent bug in a graph widget where the Y-axis displays the same number across all scales, despite expectations that numbers should increase as they go up, with a screenshot provided for illustration; no reproduction steps or environment details are fully specified.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue with the Grafana graph widget. To help us better understand and resolve the problem, I have a few questions and requests for additional information: 

1. Could you please specify the version of Grafana you are using?
2. What operating system and browser (with versions) are you experiencing this issue on?
3. It seems the screenshot link might be broken or incorrect. Could you provide a valid link or re-upload the screenshot?
4. Does this issue occur with a specific datasource or multiple datasources? If possible, please specify which datasource(s) you are using.
5. Can you recall any specific actions or configurations that lead to this issue? For instance, does it occur after updating data, changing settings, or during initial load?
6. If there is a publicly accessible dashboard or a simplified version of the panel that demonstrates the problem, it could be beneficial to share that as well.
7. Lastly, you mentioned that the bug was inside a dashboard panel. Could you clarify whether this issue has appeared in new panels as well or only existing ones?

Providing this information will greatly help us in diagnosing the issue and offering a more precise solution. Thank you for your contribution to the Grafana community!

**Comment by moxious** [comment]
Thank you for reporting this issue, @tonypowa. This appears to be a problem related to rendering graphs, which makes the [Frontend Platform project](https://github.com/grafana/grafana/projects) the most appropriate for this issue. A member of that team should be able to help you to troubleshoot the problem. It would be helpful if you can add more details like the specific Grafana version, OS, and browser you are using, and whether this happens with all data sources or a specific one.
