### ISSUE TITLE
Panel Query Data not refreshing if there is no data after query for raw data query 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#285]
### What happened?

Getting Exceptions and continuous query loading icon 

reportUnhandledError.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'length')

 at P (processDataFrame.ts:263:36)

 at u (groupBy.ts:183:14)

 at groupBy.ts:143:39

 at map.js:7:37

 at E._next (OperatorSubscriber.js:15:21)

 at M.next (Subscriber.js:34:18)

 at b._subscribe (innerFrom.js:51:24)

 at b._trySubscribe (Observable.js:38:25)

 at Observable.js:32:31

 at u (errorContext.js:19:9)

### What did you expect to happen?

panel should return no data found if there is no data for any particular filter . Then for other filter if data present then panel data should be refreshed 

### Did this work before?

Don't know

### How do we reproduce it?

1 . create panel query with no data returning 

### Environment (with versions)?

Grafana: 10

OS: all machine

Browser: all browser 

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

opensearch

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81815

**Comment by moxious** [comment]
Hi @tonypowa, it looks like this issue might belong to the **Frontend Platform project** due to the JavaScript errors originating from UI components ('processDataFrame.ts'). The team in charge of frontend development should be able to help you diagnose and fix the issue regarding the panel queries not refreshing properly when there is no data. 

Can you also clarify if you're using any plugins that might affect the data query behavior?

_Transferring this issue to the Frontend Platform project would be the appropriate next step._
