### ISSUE TITLE
Stat widget legend is inaccurate when using value options `Total`

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#287]
### What happened?

I'm using the metrics out of MinIO with the following query

```

sum(increase(minio_s3_requests_ttfb_seconds_distribution{job="minio-job",le="0.050"}[$__rate_interval]))/2

```

because the metric is reported twice, I need to divide it by two.

however if you look at the resulting unique values, they add up to `100` and that is correct, I only performed 100 requests

<img width="1274" alt="Screenshot 2024-02-06 at 9 42 24 AM" src="https://github.com/grafana/grafana/assets/18384552/63ef202d-d89f-45d6-a56c-59c83daa4edf">

but if I change the value option to `Total` the total is wrong

<img width="1275" alt="Screenshot 2024-02-06 at 9 42 51 AM" src="https://github.com/grafana/grafana/assets/18384552/cb3f9faf-4d9f-41eb-a01c-d5df49382186">

it's like it's ignoring the `/2` part of the query

### What did you expect to happen?

I expect it to show `100`

### Did this work before?

no

### How do we reproduce it?

1. Deploy a MinIO and fetch it's metrics

2. add a widget of type stat with `sum(increase(minio_s3_requests_ttfb_seconds_distribution{job="minio-job",le="0.050"}[$__rate_interval]))/2` query

3. set the display value of the stat of `count` so it shows the total of values being displayed

### Is the bug inside a dashboard panel?

yes

### Environment (with versions)?

Grafana: v10.3.1

OS: maxOS

Browser: safari

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#81997

**Comment by moxious** [comment]
**Summary**: The issue #287, opened by tonypowa, describes a problem where the Grafana stat widget legend displays an incorrect 'Total' when using value options 'Total' with a specific query that divides the result by two. The user expects a total of `100` but gets an inaccurate number, indicating that the division part of the query is ignored.

**Comment by moxious** [comment]
Hi @tonypowa,

Thank you for reporting this issue. It seems like you are experiencing problems with the Stat panel's calculation when using the `Total` option. This could potentially be an issue related to the handling of queries and visual representations in Grafana.

To ensure the right team looks into this, I'm suggesting that this might be associated with the **Grafana Metrics project**, as it involves the interaction with a datasource (Prometheus) and the display of metrics on a dashboard panel.

If you have any more information or steps that could help replicate this issue, please provide them to help the team resolve this faster.

Best regards,
The GitHub Assistant

**Comment by moxious** [comment]
**Elaboration**:


Thank you for submitting this issue, Tony. To further investigate the discrepancy you're experiencing with the 'Total' value in your Stat widget, we would benefit from a bit more information. Please provide the following additional details so we can help resolve the problem effectively: 

- A clearer screenshot or copy of the legend with the inaccurate totals. The links in your issue appear to be broken. Could you verify and re-upload the images, or provide a direct link?
- It may be helpful to include the raw data returned by your Prometheus query for both `Total` and the unique values. This will help us verify if the issue lies within the data source itself or the Grafana visualization.
- Can you confirm if you've tried experimenting with different queries or visualization options to determine whether the problem persists in different configurations?
- If possible, please provide the steps to replicate your Prometheus setup and any relevant configuration that might impact the query results.
- Lastly, do you notice any console errors in your browser's developer tools when you change the value option to `Total`? Error logs can often provide insights into underlying issues.

Thank you for working with us to diagnose and fix this issue.
