### ISSUE TITLE
Tool tip is unusable when there are too many series in a panel

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#292]
### What happened?

![Screenshot_20240208_172209](https://github.com/grafana/grafana/assets/2118079/c109a8e5-99e4-4dd0-acce-a7c2a7e267c2)

i have a graph with many series (more than the tooltip can hold) the result is not usable

### What did you expect to happen?

to have a way to see all values

### Did this work before?

don't know

### How do we reproduce it?

1. create a graph with many series

2.

3.

### Is the bug inside a dashboard panel?

![image](https://github.com/grafana/grafana/assets/2118079/90f62334-79cf-472c-8dbc-204c0ee5312c)

### Environment (with versions)?

Grafana: 10.2.1

OS: Docker container

Browser: chrome

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82177

**Comment by moxious** [comment]
**Summary**: The issue, opened by user tonypowa, describes a problem in Grafana 10.2.1 where the tooltip becomes unusable when there are too many series in a panel, as it cannot display all values.

**Comment by moxious** [comment]
**Elaboration**:


### Clarification Requested

Hello @tonypowa,

Thank you for reaching out! It seems that you're encountering an issue with tooltip overcrowding due to the presence of numerous series in a Grafana panel. To better assist you and address this issue, we would appreciate a bit more detail:

1. **Series Quantity**: Can you specify the exact number of series you have in the graph when the tooltip becomes unusable?

2. **Screenshot Verification**: The screenshot link provided appears to be broken. Could you please provide an updated link or re-upload the screenshot?

3. **Steps to Reproduce**: You've started detailing the steps to reproduce but stopped at step 1. Could you continue listing the steps you follow to encounter the issue?

4. **Did this work before?**: You mentioned you're not sure if it worked before. If possible, could you check an earlier version of Grafana to see if the issue persists there?

5. **Detailed Environment**: While you've provided some environment details, knowing the specific Docker image tag you're using for Grafana might help. Additionally, can you confirm which version of Chrome you are using?

6. **Datasource Details**: Information on the datasource(s) you're using (e.g., Prometheus, MySQL) might be relevant. Sometimes datasource-specific behavior can influence how Grafana displays tooltips.

7. **Console Errors**: Are there any errors in the browser's developer console when the tooltip issue occurs? If so, please include them.

8. **Configuration**: If you have customized Grafana's configuration or tooltip settings, sharing those configurations may shed light on the issue.

By providing these additional details, we can better understand the issue and work towards a resolution. Thank you in advance for your cooperation!

Best,
The Grafana Open Source Community Team
