### ISSUE TITLE
Dashboards: Exporting for external use

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#295]
### What happened?

While exporting boards for external use it generated data source UID variable e.g. "$DS_PROMETHEUS". It is only useful when you have only one other environment. In my case I have three different environments and using helm charts to provision boards. In other two environment it throws error "$DS_PROMETHEUS not found" because though the data source is same e.g. prometheus UID is different.

### What did you expect to happen?

It should some how auto detect the DS UID and should set it in background.

### Did this work before?

No

### How do we reproduce it?

1. In my case I have three different environments and using helm charts to provision boards. In other two environment it throws error "$DS_PROMETHEUS not found"

2.

3.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 10.2.2

OS: Windows

Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus and Loki

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82260

**Comment by moxious** [comment]
**Summary**: Issue #295, opened by tonypowa, concerns a problem with exporting dashboards for external use in Grafana. The exporter generates a data source UID variable that does not work in multiple environments with different UIDs, causing an error message '$DS_PROMETHEUS not found' in environments other than the one where the dashboard was exported.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for submitting the issue, tonypowa! To help us better understand and address your concern about the data source UID variable during export, could you please provide the following additional information: 

- Can you share the error logs or screenshots where '$DS_PROMETHEUS not found' is being shown?
- Could you give an example of how your Helm charts are provisioning the dashboards? Specifically, it would be helpful to see the relevant parts of the values.yaml or any templates that are being used.
- Has there been any customization done to the data sources in your environments that might affect UID generation or recognition?
- Are you using any sort of version control or configuration management for your dashboards that could be affecting the UIDs between environments?

To reproduce the issue more effectively, it would also be valuable if you could provide a minimal example of a dashboard definition (in JSON) that is failing to import correctly due to the UID issue.

Once we have this information, we'll be in a better position to investigate the problem and suggest possible solutions. Thank you in advance for your cooperation!

**Comment by moxious** [comment]
Hello @tonypowa, it seems like your issue is related to dashboard provisioning and data source referencing in multi-environment setups, which might be relevant to the **Dashboards Sharing squad** project. I will label this issue accordingly so that the appropriate team can take a look.

```json
"labels": ["team/dashboards-sharing"]
```

In the meantime, you might want to explore the use of environment variables in your Helm charts to manage data source UIDs across different environments.
