### ISSUE TITLE
Dashboards: CSV download does not show same values as legent

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#297]
### What happened?

with a timeseries graph against prometheus: ie avg by (pod)(kube_pod_container_resource_requests{resource="memory"})

it shows a line graph for each pod over last 24 hours

and it shows a legend with 2 columns (pod and memory in bytes)

when clicking download CSV on the results it seems to only download historical per 5 min entries for just 1 pod

### What did you expect to happen?

would like to download exactly what the 2 column legent under the panel shows. ie all distinct pod names and last byte value for each one

### Did this work before?

no

### How do we reproduce it?

1. create timeseries panel that runs an expr against prometheus

2. click download csv

### Environment (with versions)?

Grafana: 10.2.1

### Grafana platform?

Kubernetes

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82410

**Comment by moxious** [comment]
**Summary**: The issue on Grafana reported by tonypowa describes a discrepancy when downloading CSV data from a timeseries dashboard panel; the CSV contains historical data for a single pod, rather than the latest data for all pods as displayed in the dashboard legend.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue you’ve encountered with the CSV download functionality within dashboards. In order to assist you effectively and address the issue, we need a little more information. Could you please provide the following details? It'll help us in diagnosing the problem accurately:

1. Could you confirm if other panels or queries face similar issues with CSV downloads, or is it just this specific query that's causing problems?
2. When you mention 'historical per 5 min entries', does this apply to the series on the graph as well, or are you expecting aggregations over a different time period in the CSV?
3. It would be helpful to see a screenshot of the panel showing the legend and the graph, alongside the resulting CSV file (with any sensitive data anonymized).
4. Can you confirm whether you have tried different browsers or systems to download the CSV, to rule out client-side issues?
5. Are there any errors or logs in Grafana that appear when you attempt to download the CSV file?
6. Providing the exact query you are using for the timeseries panel would be beneficial.

Lastly, if you can provide detailed reproduction steps or even a minimal dashboard JSON that demonstrates the issue, that would be incredibly useful.

Once we have this information, we'll be better equipped to figure out the cause and find a potential solution. Thank you for your collaboration!
