### ISSUE TITLE
Alerting: routing on labels generated by query works in routing preview but is ignored on real alerts

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#298]
### What happened?

We have an alert on a prometheus query on metrics of things happening on the monitoring host (log volume going into loki, big changes in the number of metrics received) - but soon realized that these alerts better go to the teams (represented by a label) responsible for the group of machines affected. 

We already had alert routing (notification policies) active on a label service=somename sending the corresponding entry to the respective team contact point. 

The metrics already had a tag name the same as in this service=xxx routing. The label name was different, but that could be adjusted with a "label_replace":

Source: prometheus

Query: `label_replace(logs:rate:job,"service","$1","job","(.+)")`

So under "Labels and notifications" in the alert page, I would just not set a label - but the label would be set by the query.

Clicking on "Preview routing", this is recognized and works:

![grafana_routing](https://github.com/grafana/grafana/assets/2482093/a03ee473-a46b-45b0-925e-c68a24ae5fcc)

But when an actual alert is triggered, it is using the "Default policy" contact point instead of what the preview shows

### What did you expect to happen?

when an actual alert is triggered, it is using the "Default policy" contact point instead of what the preview shows

### Did this work before?

no

### How do we reproduce it?

1. make a query that produces labels

2. create routing policies that react to the labels

3. create an alert and press "preview routing"

4. trigger the alert and see where it goes

### Environment (with versions)?

Grafana: 10.3.1

OS: debian stable

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

prometheus (did not try others)

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82466

**Comment by moxious** [comment]
Hi @tonypowa! This seems like it might be an issue specific to the **Alerting project**. Since you're describing a situation where alerts are not being routed according to the labels generated by a Prometheus query, which seems to involve the notification policies feature of Grafana's alerting system, they would be the most suited team to address this discrepancy between the routing preview and the real alert behavior.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue regarding alert routing not working as expected with labels generated by queries. It's great to see that you've already provided a detailed explanation and some initial steps on how to reproduce the issue. However, to better assist you and identify the root cause, we may need a little more information. Could you please provide the following details? 

1. Can you share the **exact version** of Prometheus you are using along with Grafana 10.3.1?

2. Have you noticed any relevant **logs** on the Grafana server when the alert is triggered and routed to the default contact point instead of the expected one? These logs could provide clues as to why the alert isn't being routed correctly.

3. Could you confirm whether this setup worked with any **previous versions** of Grafana, or is this a new alerting setup that has not been tested on older versions?

4. You mention that the routing works in the preview but not when the alerts are actually triggered. Is there any **difference** in the configuration between the time you use the Preview feature and the actual alert trigger scenario?

5. It might also be beneficial if you can provide us with a **configuration snippet** showing how the notification policies are set up, ensuring any sensitive information is redacted.

6. Lastly, if you are able to **consistently reproduce** this issue, would you be willing to share a **step-by-step guide** or a **screencast** showing the process from the setup of the query to the failure of the routing on actual alert triggering?

Once we have this information, we'll be better positioned to help troubleshoot the issue. Looking forward to your response!

**Comment by moxious** [comment]
**Summary**: The issue concerns an alert routing problem in Grafana, where despite labels being correctly generated by a Prometheus query and properly previewed in the routing setup, actual triggered alerts are incorrectly using the default contact point rather than the specified team contact based on the label, deviating from expected behavior.
