### ISSUE TITLE
Product Area: Prometheus Data Source does not show unique labels on "Auto" legend

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#302]
### What happened?

![ksnip_20240215-174959](https://github.com/grafana/grafana/assets/110499773/9afafa4c-2979-49e4-a66b-8273713ca7c2)

### What did you expect to happen?

The help text for the "Auto" legend under the prometheus data source says "Only includes unique labels". From the screenshot, I was expecting the legend to be only unique labels, but that was not the case. 

### Did this work before?

Unsure

### How do we reproduce it?

1. Ship metrics via prometheus where the same metric has different label values

2. Try and visualize the data in Grafana with the Auto legend.

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Grafana 9.5.1

OS: Ubuntu 22.04

Browser: Chrome

### Grafana platform?

Kubernetes

### Datasource(s)?

Prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#82870

**Comment by moxious** [comment]
Hi @tonypowa, thank you for reporting this issue. It seems like you're encountering an issue with the Prometheus data source within Grafana. I'll transfer this issue to the **AWS DataSources project** as it's the best match from the available options, and the Prometheus data source is often tightly coupled with cloud provider integrations like AWS's managed Prometheus service. The team responsible for AWS integrations should have insights into data source specific issues like the one you've described. 

In the meantime, please double-check if the issue persists across different versions or setups and if there's any specific configuration that might be affecting the legend functionality.

/cc @aws-datasource-team

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thanks for taking the time to report this issue. Based on the information you’ve provided, we have a good starting point but it would be beneficial for us to gather a bit more detail to effectively address your concern. Here are a few questions and suggestions that can help us understand the problem better:

- Could you confirm if the screenshot is accessible? The link provided seems to be broken, and we are unable to view the image. If possible, could you re-upload the screenshot directly to this issue or verify the link is correct?

- When you mention that the legend does not only include unique labels, could you describe in more detail what you are seeing instead? Providing the exact legend values or another screenshot illustrating the issue would be very helpful.

- Have you encountered this behavior on any other Grafana version, or have you only noticed it on version 9.5.1?

- Regarding the reproduction steps, could you provide an example of the PromQL query you're using? This can sometimes be relevant if the issue is related to how the query is constructed.

- Additionally, could you specify if you're aware of any particular configurations or settings within Grafana or Prometheus that might affect the legend behavior?

Once we have the additional information, we’ll be better positioned to provide assistance or escalate the issue for further investigation. Thank you again for your contribution!
