### ISSUE TITLE
Alerting: reordering "grouped" alert rules removes alerts filtered via search

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#306]
### What happened?

When reordering rules inside a "filtered" evaluation group, all alerts that were not present in filtered list get removed.

### What did you expect to happen?

Alert rules not to be deleted when sorting a filtered evaluation group.

I would even expect that the sort list content would NOT be affected by rule filters via search dialog.

### Did this work before?

n/a

### How do we reproduce it?

1. create 3 alert rules using the same evaluation group, e.g. "a1", "b1" and "b2"

2. filter alerts, e.g. search for "b"

3. reorder rules for the evaluation group, e.g., move "b2" to top position

4. clear all filters

5. the alert rule "a1" is gone

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana: 10.3.3

OS: linux

Browser: chrome

### Grafana platform?

Docker

**Comment by moxious** [comment]
Hi @tonypowa, thanks for reporting this issue. It appears to be related to the alerting functionality within Grafana. I am categorizing this under the **Alerting project** so the right team can take a look at the unintended behavior with alert rule reordering in the evaluation groups. 

/team Alerting

**Comment by moxious** [comment]
**Summary**: In Grafana, reordering alert rules within a filtered evaluation group causes any alerts not visible due to the filter to be deleted, contrary to the expectation that the alert rules would not be affected by search filters.

**Comment by moxious** [comment]
**Elaboration**:


### Thank you for submitting an issue report, Tony!

It seems like you're encountering a problem with reordering rules in a filtered evaluation group within Grafana. To help us understand and address this issue more effectively, I have a few additional questions and requests:

- **Reproduction Steps:** You've described a method to reproduce the issue, which is fantastic. Could you please clarify if you are using the Grafana UI or the API to reorder the alert rules? Screenshots or screen recordings demonstrating the problem would be incredibly helpful.

- **Rule Configuration:** Is there any additional configuration to the alert rules we should be aware of that could influence this behavior?

- **Logs:** Are there any relevant server or browser console logs that appear when you perform the reordering? Mentioning any error messages or warnings could provide clues about what's going wrong.

- **Grafana Setup:** Is this a standalone Grafana instance or part of a larger monitoring setup? Additionally, is it a fresh install or an upgrade from a previous version?

By providing this extra information, we'll have a much better chance of pinpointing the root cause of the issue and working on a fix. Your collaboration is key in helping us improve Grafana for everyone. Thank you!
