### ISSUE TITLE
Math expression broken in v10.3.3

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#313]
### What happened?

Grafana Math expression has broken since v10.3.3, and make charts mess up.

before: 

![image](https://github.com/grafana/grafana/assets/3634305/8319e9b9-345a-4b7d-9413-d2e9762d70a5)

after:

![image](https://github.com/grafana/grafana/assets/3634305/a7d225d3-9a37-45bf-af5f-7da622f23aeb)

### What did you expect to happen?

Grafana Math expression works like 10.2.4

### Did this work before?

Yes, it works fine in v10.2.4

### How do we reproduce it?

1. upgrade the version from 10.2.4 to 10.3.3

2. use multi-frame data, and make 2 queries and one Math expression, let $A -$B

3. $C should be the result of $A -$B, but now it's messed up.

### Is the bug inside a dashboard panel?

Yes

### Environment (with versions)?

Grafana: v10.3.3

OS: Ubuntu

Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Elastcisearch

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#83562

**Comment by moxious** [comment]
Hi @tonypowa, it sounds like you're experiencing an issue related to the processing of Math expressions within dashboard panels. This could be associated with the **Dashboard Sharing squad**, as they handle features related to creating and managing dashboards, which includes expression evaluation within panels. Would you be able to provide more details on the Math expression you're using and any error messages you see in the Grafana UI or the browser's dev tools console? This could help the team in diagnosing the problem more effectively.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reporting this issue with the Math expression in Grafana v10.3.3. In order to help address your concern more effectively, there are a few clarifications and additional pieces of information that would be extremely beneficial:

1. **Grafana Logs**: Would it be possible for you to provide any related Grafana server logs? They may contain errors or warnings that can help identify the root cause of the issue.

2. **Math Expression Details**: What is the exact Math expression you are using? Please provide the formula you tried to implement. This could help in replicating the issue more precisely.

3. **Panel JSON**: Exporting and sharing the panel JSON where the Math expression is used could help us reproduce the environment and problem you're facing.

4. **Screenshot Accessibility**: It looks like there might be an issue with the links to your screenshots. Instead of getting directed to the images, we're directed to a 404 page. Could you verify the links or provide the images in another way?

5. **Error Messages**: Are there any error messages displayed in the Grafana UI or browser console when the issue occurs? Sharing these would provide insights into what might be going wrong.

6. **Data Examples**: Could you provide a small, anonymized sample of the data frames $A and $B that you use in your queries?

7. **Steps To Reproduce**: The reproduction steps are helpful, but could you provide a bit more detail on the queries that you are using to produce $A and $B? A textual description or example query can help us set up the exact scenario.

Once we have this information, it will be significantly easier for the Grafana community and maintainers to investigate the issue and suggest a fix. Thank you for working with us to improve Grafana!
