### ISSUE TITLE
Alerting: external alertmanager false resolve messages

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#317]
### What happened?

I 'm trying to provide free customization of Alert queries inside Grafana, but I prefer to use prometheus alertmanager for message delivery. 

I have found that a typical setup sends one message, which after a few minutes is declared resolved inside prometheus alertmanager. Of course, this is not correct. Notification should only be sent when these conditions actually occur.

Indeed, in the alertmanager web interface I see the alert for a short time

### What did you expect to happen?

Send one alert message when fail. Then send another resolve message, if query conditions are ok.

### Did this work before?

Doesn't know

### How do we reproduce it?

1. setup grafana with prometheus and alertmanager

2. setup message routing inside alertmanager 

3. add Alert Query and select contact point

4. wait for fire message

5. wait some time for **FALSE** resolve message

### Environment (with versions)?

Grafana: 10.3.3

### Grafana platform?

Docker

### Datasource(s)?

Loki

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#83795

**Comment by moxious** [comment]
**Summary**: User tonypowa reports an issue with Grafana where Prometheus Alertmanager sends false resolve messages shortly after an initial alert, despite conditions for resolution not being met. The expected behavior is to only send resolution notifications when the specified conditions are satisfied.

**Comment by moxious** [comment]
Hi @tonypowa,

Thanks for reporting the issue with Alerting and the external Alertmanager integration. Based on the details of your report, it seems like this issue would be best suited for the **Alerting project** as it directly deals with alert notifications and behavior which is part of the Alerting system in Grafana.

Can you confirm if you have set up any silencing or inhibition rules in Prometheus Alertmanager that might affect the alert lifecycle?

/label alerting

**Comment by moxious** [comment]
**Elaboration**:


### Follow-up Questions for Clarification

Hello @tonypowa, thank you for reporting the issue with the alerting in Grafana in combination with Prometheus Alertmanager.

In order to better understand and assess the problem, I'd like to ask a few questions and, if possible, request additional information:

1. Could you provide the exact configuration (without any sensitive information) that you are using for Prometheus Alertmanager? It's crucial to understand how the alert routing and grouping are set up.

2. Are there any specific rules or settings you can share for the Alert Queries in Grafana that leads to these false resolve messages?

3. You mentioned that you see the alert for a short time in the alertmanager web interface. Could you please provide a screenshot of this, along with any logs from Prometheus Alertmanager during the time the issue occurs?

4. Has the false resolve message ever followed the correct behavior you're expecting in any of your previous configurations, or is this issue consistently happening every time?

5. You said you set up message routing inside alertmanager. Could there be any specific configuration there that may cause the resolve messages to be sent out prematurely?

6. Can you please try reproducing the issue and capturing detailed logs from both Grafana and Prometheus Alertmanager when the alert is fired and when the false resolution message is sent?

By providing this additional information, we can get a clearer picture of the root cause. Once again, thank you for participating in the open-source community, and we're looking forward to helping you resolve this issue.
