### ISSUE TITLE
Grafana: Unable to set httponly for grafana cookie

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#318]
[###]

![grafana cookieext](https://github.com/grafana/grafana/assets/94673081/893f4c15-99f8-48e4-8228-8bbe40752018)

What happened?

Unable to set httponly flag on grafana cookie, please see attachment

cookie:

grafana_session_expiry

### What did you expect to happen?

all cookies are set httponly

### Did this work before?

no it never worked

### How do we reproduce it?

1. open dev tools in browser

2. load a web page

3. verify cookie's security flags

### Environment (with versions)?

Grafana:10.3.1

OS: RHEL9.3 UBI

Browser: EDGE, FIREFOX

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#83810

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for bringing this to our attention. In order to help us dig deeper into the issue with the `httponly` flag for Grafana cookies, we'll need some additional details. Could you please provide the following information to assist us in identifying the problem more precisely?

1. In the steps to reproduce the issue, could you specify the exact URL or type of web page (if possible, a public endpoint) you are loading when you observe the cookie security flags?
2. Can you confirm whether you are using the standard installation of Grafana or if you've applied any custom configurations or proxies that might intercept or alter HTTP headers?
3. Have you altered any settings in `grafana.ini` or environment variables that pertain to session cookies or security?
4. It appears that the linked screenshot did not load correctly. Could you please re-upload the image or provide a clear step-by-step description of what you're seeing in the dev tools?
5. Lastly, if you have attempted any workarounds or solutions to try to force the `httponly` flag, such as custom middleware or headers, please share those attempts as well.

The more detailed information you can provide, the better we can understand the context and specifics of the issue. Thanks!
