### ISSUE TITLE
Dashboards: The share dialog for a dashboard is broken and always leads to the 'share dashboard' dialog

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#324]
### What happened?

If you want to share a dashboard the URL always contains the parameter to open the share dialog: `&shareView=link`

### What did you expect to happen?

The generated URL links to the dashboard, not the dialog

### Did this work before?

It didn't stand out to me in the past but I can't tell for 100%

### How do we reproduce it?

1. Open a dashboard

2. Click on share

3. Inspect the generated URL and test it in another window

### Is the bug inside a dashboard panel?

All dashboards.

### Environment (with versions)?

Grafana: v10.3.3 (252761264e)

OS: MacOS 14.4

Browser: Firefox 123.0.1 (64 bit)

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#84340

**Comment by moxious** [comment]
Hi @tonypowa, thanks for reporting this issue. It seems like you are experiencing problems related to sharing dashboards in Grafana. This issue is best associated with the **Dashboards Sharing squad** as they handle features and bugs related to sharing dashboards within Grafana. I'll tag this issue for their attention.

/cc @dash-sharing-squad

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reporting the issue with sharing dashboards. To help us investigate this further, could you please provide the following additional information? 

1. Can you confirm if this issue occurs with all browsers or if you've observed it only on Firefox?
2. Have you tried this with any other Grafana versions?
3. Are there any console errors in Firefox when you try to share a dashboard? If yes, could you please share them?
4. Could you provide a screen recording or screenshots depicting the issue?
5. Do you use any custom plugins or scripts that might affect the share functionality?
6. You mentioned that this is on Kubernetes; could you share more details about your deployment, such as the use of Ingress or any proxy configuration involved?

Any additional context or details you can provide will be greatly appreciated and help us in diagnosing the problem more efficiently. Thank you!

**Comment by moxious** [comment]
**Summary**: The issue (#324) is about the share dialog for dashboards in Grafana v10.3.3 not functioning correctly; instead of linking directly to the dashboard, the generated URL always opens the share dialog. The issue is still open, needing verification if it previously worked, and how to consistently reproduce it.
