### ISSUE TITLE
Table: "Organize fields by name" transformation order rearranges after reloads

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#332]
### What happened?

I have a dashboard that contains rows each with a table per application. The tables uses a InfluxDB connection to get data and the result is re-ordered by using transformation ("organize fields by name") to get the wished order.

When opening the transformation tab and pressing the browser-reload the order changes which causes in a table with a wrong order if the columns.

<img width="635" alt="image" src="https://github.com/grafana/grafana/assets/41045137/e5a7a4dd-5d40-4ea6-8852-5c3dc5baa964">

The bahaviour changes also within the rows & table visualization - means, first app with a row and a table shows the wrong order and the second app with a row and a table shows the right one.

### What did you expect to happen?

I expect, that the defined order in the transformation tab remains the same for all rows after every reload.

### Did this work before?

Never experienced the behaviour before.

### How do we reproduce it?

1. Dashboard with a table per app in a row (row option)

2. changing the order by using a transformation

3.pressing the reload of the browser 

### Environment (with versions)?

Grafana: 10.3.3

OS: Linux

Browser: chrome

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

InfluxDB

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#84724

**Comment by moxious** [comment]
**Summary**: The issue, reported by tonypowa, involves a Grafana dashboard where rows containing tables that use an InfluxDB connection lose their organized field order after a browser reload, despite being set up with a 'organize fields by name' transformation. This results in tables displaying columns in an incorrect order, which varies inconsistently across different rows or table visualizations within the dashboard.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa! Thank you for reporting the issue with the 'Organize fields by name' transformation in Grafana. In order to better understand and resolve the problem you're experiencing, it would be helpful to gather a bit more information. Here are some guided questions that could shed more light on the issue: 

- Could you provide the step-by-step transformation configuration that you have used? A detailed description or a screenshot of transformation settings would be of great assistance. 
- Have you noticed if the issue persists across different browsers or is it isolated to Chrome? 
- When the order changes, is there a pattern to the new order (e.g., alphabetical, by data type), or does it seem random? 
- Can you verify if this happens for all dashboards where you use this transformation, or is it specific to a particular dashboard? 
- Is there any console error or warning in the browser developer tools when the issue occurs? 
- Are there any specific plugins or scripts running on your dashboard that could be interfering with the table's order? 

If you have a JSON model of the dashboard or the specific panel that you could share, that would also provide valuable context. Additionally, confirming that the issue occurs with different InfluxDB sources or only a specific one would also be helpful.

This information will help us replicate and diagnose the issue more accurately. Looking forward to your response!

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you're encountering an issue with table visualizations in Grafana and their behavior after applying transformations and subsequent reloads. It might be linked to how the state of the dashboard and panels is persisted. Since this involves the core dashboard functionality, which includes the ability to apply transformations to panel data, the most appropriate team to take a look at this would be the **Frontend Platform project**. They handle the UI components and the overall user experience for Grafana.

```markdown
Could you please provide some additional information?

1. Does this issue occur consistently across other browsers or is it specific to Google Chrome?
2. Have you tried creating a minimal dashboard with just one table panel and the transformation to see if the issue persists there as well?
3. Could you share a JSON model of the dashboard (with sensitive data removed), so the team can attempt to reproduce the issue with exact settings?
```

Meanwhile, tagging this for the attention of the **Frontend Platform project** could be helpful. They need to verify if the transformation state persistence is working as expected across browser sessions.
