### ISSUE TITLE
Grafana Contact points with Webhook, filled Basic Authentication, but test found 401 unauthorized

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#336]
1.When use Grafana Contact points with Webhook to send alert notification, 

2.filled URL, HTTP Method, HTTP Basic Authentication - Username, HTTP Basic Authentication - password,

3.Before save contact points, tested successfully

4.After save contact point(When click save found call /grafana-oncall-app/settings api got and 404 error, and error message"Plugin not found ,no installed plugin with that id") ,and try to test again, but test found 401 unauthorized

I am using grafana 10.0.3. Any one can help on my issue?

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#85694

**Comment by moxious** [comment]
**Summary**: User tonypowa reports an issue with Grafana Contact points for Webhooks where after setting up basic authentication and initially receiving a successful test, subsequent tests post-save result in a 401 unauthorized error, alongside a 404 error related to the plugin not being found.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa! Thank you for reaching out with your issue. To better assist you with the problem you're encountering with Grafana contact points and webhooks, I'd like to ask a few clarifying questions. This will help us understand your issue in more depth and provide accurate guidance or a solution.

1. Could you confirm that the credentials used for HTTP Basic Authentication have not changed or expired since your successful test and the observed 401 error?

2. Is it possible for you to provide us with the detailed steps you took when setting up the contact point, including any screenshots of the configuration (with sensitive information redacted)?

3. Can you include the Grafana server logs from the time when you're attempting to test the saved contact point? These logs might contain additional information that can help diagnose the issue.

4. Please make sure that the plugin you are expecting to use is correctly installed. Could you provide us with the output of the Grafana CLI command `grafana-cli plugins ls` to confirm the plugin is listed?

5. Have you made any recent changes to the Grafana instance or its configuration before this issue started occurring?

6. Could you also please provide the version of the plugin you're having issues with, if applicable?

Again, thank you for submitting this issue. The detailed information you provide next will be vital to accurately address your concern.

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you are encountering an issue with alert notifications and authentication in Grafana. This might be related to a problem with either the Backend platform project or the Alerting project. However, based on the details you provided, the Alerting project is likely the best fit for this issue because it pertains to contact points configuration and notifications, which are part of the alerting functionality in Grafana.

```
/project Alerting
```
