### ISSUE TITLE
Grafana UI: `Modal` - Replace HorizontalGroup with Stack

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#339]
What is this feature?

This is part of the epic https://github.com/grafana/grafana/issues/85510

Why do we need this feature?

To replace deprecated layout components with new ones.

Who is this feature for?

Everybody

**Which issue(s) does this PR fix?**:

Fixes #

**Special notes for your reviewer:**

**Before:**

![Captura de pantalla 2024-04-08 a las 18 52 17](https://github.com/grafana/grafana/assets/65417731/57c80de8-4cd8-4e6c-8433-b03e12d47cbe)

**After:**

![Captura de pantalla 2024-04-08 a las 18 53 10](https://github.com/grafana/grafana/assets/65417731/e16a1d80-3392-4e89-b305-99e8944e17ef)

Please check that:

- [ ] It works as expected from a user's perspective.

- [ ] If this is a pre-GA feature, it is behind a feature toggle.

- [ ] The docs are updated, and if this is a [notable improvement](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/#how-to-determine-if-content-belongs-in-a-whats-new-document), it's added to our [What's New](https://grafana.com/docs/writers-toolkit/writing-guide/contribute-release-notes/) doc.

**Comment by moxious** [comment]
**Summary**: Issue #339, titled 'Grafana UI: `Modal` - Replace HorizontalGroup with Stack', is open and discusses updating Grafana's UI components by replacing deprecated layout components with new stack components as part of a larger epic. There is one screenshot showing the 'Before' state and another showing the 'After' state, and the issue is awaiting a review to ensure user expectations and documentation are updated accordingly.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, 

Thank you for submitting this issue and contributing to the project! To better understand and address the issue, could you please provide some additional information?

1. Could you clarify what the expected behavior is after replacing the `HorizontalGroup` with `Stack`? Are there any specific UI benefits or functionality improvements that you expect to see?

2. The issue mentions that this is part of an epic. Could you explain how this particular change fits into the larger goals of the epic mentioned in the link?

3. While you've provided a 'Before' and 'After' screenshot, the links seem to be broken. Could you please re-upload or provide working links to the images so we can visually compare the changes?

4. Could you provide steps to reproduce the current behavior that you're intending to improve with this issue? This would help us see the issue firsthand.

5. Have you already made changes in a branch that we could look at? If so, please share the link to your Pull Request or the branch.

6. You checked that it works as expected from a user's perspective. Could you share a brief outline of the tests you performed to validate this?

7. Finally, please confirm if you have already added documentation or if help is needed to update the documentation.

Providing this additional context will help maintainers and other contributors understand and triage your issue more effectively.

Looking forward to your response!

Best regards,
The Grafana Team
