### ISSUE TITLE
Alerting: Preview routing is using cached notification policies

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#340]
### What happened?

- I clicked `Preview routing`

- The routing was wrong because my notification policy was broken

- I fixed the notification policy in new tab

- I clicked `Preview routing`

- It showed old and broken routing

- I refreshed the alert review tab (which cleared all my changes that I was testing)

- I reapplied all my changes

- I clicked `Preview rounting`

- It showed correct routing that I wanted to see

### What did you expect to happen?

That I do not need to refresh the whole tab to get new notification policies in the alert edit view.

### Did this work before?

No

### How do we reproduce it?

- I clicked `Preview routing`

- The routing was wrong because my notification policy was broken

- I fixed the notification policy in new tab

- I clicked `Preview routing`

- It showed old and broken routing

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 1.4.1

OS: Ubuntu 22.04.4 LTS

Browser: Chrome Version 123.0.6312.122 (Official Build) (64-bit)

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#86756

**Comment by moxious** [comment]
**Summary**: Issue 340 is OPEN where `Preview routing` is not reflecting changes in the notification policies without refreshing the alert review tab, an unexpected behavior encountered in Grafana 1.4.1 on Ubuntu, using Chrome.

**Comment by moxious** [comment]
Hi @tonypowa, it sounds like you're experiencing caching issues with the alerting system. This looks like it might be related to the **Alerting project**. I'll label this issue for the Alerting project team to take a look at the caching behavior of notification policies in the preview routing feature. 

```json
{
 "labels": ["project/alerting", "type/bug"]
}
```
Thank you for the detailed report and steps to reproduce the issue!

**Comment by moxious** [comment]
**Elaboration**:


### Need Additional Information

Hello @tonypowa,

Thank you for reporting the issue with the 'Preview routing' feature within Grafana. While you have provided a good outline of the steps that lead to the problem, we need a bit more detail in order to fully understand and address the issue.

Could you please provide the following additional information?

1. **Steps to Reproduce:** It would be extremely helpful if you could provide more precise steps to reproduce the issue. This includes the specifics of where the 'Preview routing' option can be found, and the exact process of fixing the notification policy in a new tab. Are there any particular settings or conditions that we need to imitate?

2. **Expected vs. Actual Behavior:** You've explained that you expected the routing to update without needing to refresh the page. Can you provide more details on how this functionality should ideally operate? Is there an indication that changes are supposed to be live-updated, or is this a new feature request?

3. **Error Logs / Console Output:** Can you check if there are any errors in the browser's Developer Console when you experience the issue? Additionally, Grafana server logs may hold clues to what's going wrong. Please share any error messages or relevant log excerpts if possible.

4. **Screenshots / Screen Recording:** Visuals can be very helpful in diagnosing UI or UX problems. If you can safely share a screenshot or a screen recording of the issue occurring (ensuring no sensitive information is displayed), it would greatly help us understand the problem.

5. **Frequency of the Issue:** Is the issue consistently reproducible following the steps you mentioned, or does it occur intermittently?

6. **Configuration Details:** Are there any specific configuration settings or customizations within Grafana that you think might be affecting this behavior? If so, details of these configurations could be relevant.

Once we have this additional information, we will be better equipped to investigate the issue further. Your efforts in helping us understand this problem are much appreciated!

---

Thank you for contributing to our community with your issue report.

Best regards,
The Grafana Team
