### ISSUE TITLE
Alerts are sent to telegram topics - but the image-renderer breaks it

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#357]
### What happened?

Hello!

Grafana 10.4.2 - thanks for the opportunity to send telegram alerts to individual topics.

In our team we use image-renderer. And when distributing alerts across topics, everything breaks down - pictures are sent as messages to the General or Main channel. Can anything be done about this?

After all, the meaning of the whole idea with topics in this case is lost

### What did you expect to happen?

The ability to receive alerts on topics with images

### Did this work before?

no

### How do we reproduce it?

1.

2.

3.

### Is the bug inside a dashboard panel?

no

### Environment (with versions)?

Grafana:10.4.2

OS:Linux 6.1 amd64

Browser:

### Grafana platform?

Docker

### Datasource(s)?

VictoriaMetrics

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88044

**Comment by moxious** [comment]
**Summary**: The issue, opened by user tonypowa, reports a problem where alerts with images sent to individual Telegram topics in Grafana 10.4.2 are being incorrectly routed to the main channel due to an issue with the image-renderer, thereby defeating the purpose of having topic-specific alerts.

**Comment by moxious** [comment]
Hi @tonypowa, it seems like you are experiencing an issue with Grafana's alerting functionality and image rendering when using Telegram as a notification channel. I believe this issue is relevant to the **Alerting project**. The team responsible for alerting features may have insights into how alert images can properly behave with topic-based notifications in Telegram. I recommend transferring this issue to their attention for further assistance.

**Comment by tonypowa** [comment]
alerting + sharing squad
