### ISSUE TITLE
Parts of panel editor are dark when light theme is used.

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#359]
### What happened?

After I switched from Dark to Light theme in preferences, the panel editor has some dark background parts and dark text, which makes it unreadable. Panel selector drop-down also uses portions of dark theme. No amount of page refreshes fixes this.

![image](https://github.com/grafana/grafana/assets/2095278/dce6f7ac-ade9-4a5d-b405-d967dbfb9f12)

![image](https://github.com/grafana/grafana/assets/2095278/3c3d7105-db62-42ad-b9e8-615b1ecf6b8b)

### What did you expect to happen?

The dark theme should not override portions of light theme.

### Did this work before?

Don't know, our IT team has recently deployed Azure-hosted Grafana, and it's been like this the whole time (the version of grafana didn't change)

### How do we reproduce it?

Happens to me every time try to edit any panel with Light theme selected in preferences.

### Environment (with versions)?

Grafana: 10.4.1, hosted by Azure

OS: Windows 10

Browser: Edge

### Grafana platform?

Other

### Datasource(s)?

not tied to any datasource

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88126

**Comment by moxious** [comment]
Hi @tonypowa, 

Thank you for reporting this issue. Based on your description, it seems like this could be related to the interface rendering in the Frontend Platform project. I will label this issue for the frontend team to look into the theme inconsistencies you're experiencing.

Best,
Your Helpful GitHub Assistant
```
/project Frontend Platform project
```

**Comment by moxious** [comment]
**Summary**: The issue is about the panel editor in Grafana having dark themed parts, such as background and text, despite switching to a light theme, which causes readability issues. The problem persists after page refreshes and happens every time a panel is edited with the light theme selected.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reaching out and reporting the issue you've encountered with Grafana's theme settings. In order to help us better understand the problem and facilitate a swift resolution, could you please provide us with additional information? Here are some clarifying questions and requests: 

1. Could you confirm if the issue persists in other browsers or in incognito/private browsing mode in Edge?

2. Can you check if there are any browser extensions that might be affecting the styles of the Grafana UI? If possible, please try disabling them and see if the issue still occurs.

3. Is it possible for you to log in using another computer or user profile to see if the problem is specific to your user account or your current computer's setup?

4. Have you observed this issue on any other Dashboards or Panels, or is it only happening on a specific one?

5. It would be helpful if you could look into the browser's developer console for any errors when the issue occurs and provide us with a screenshot or copy of those errors.

6. Are other users also experiencing the same issue, or does it seem to be isolated to your account?

7. Lastly, the image links you've provided seem inaccessible. Could you please re-upload the images directly to the issue or verify the links so that we can view the screenshots?

Your cooperation in providing these details will be much appreciated and will help our team address the issue more effectively.

Thank you!
