### ISSUE TITLE
Grafana 11: slow load of dashboard

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#360]
### What happened?

We have dashboard for system metrics / node_exporter. There is variable filter by `node_boot_time_seconds`, this query in prometheus over 24h is resulted in 0,5s on our side ~800 servers.

After upgrading grafana to 11.0.0 is stucked on 2 queries viz screenshot and the dashboard load hang until those 2 queries returned data

<img width="1032" alt="Screenshot 2024-05-21 at 16 06 54" src="https://github.com/grafana/grafana/assets/13994937/2785c4fa-156f-4902-8d01-7f0ff70c4cdb">

If i downgrade back to 10.4.3 the dashboard load <1s vs ~7s on 11.0.0

Load time is the same with scenes feature enable and without it.

### What did you expect to happen?

Load time will be the same.

### Did this work before?

yes

### How do we reproduce it?

1. Upgrade to 11.0.0

2. Load dashboard

### Is the bug inside a dashboard panel?

whole dashboard

### Environment (with versions)?

Grafana: 11.0.0

OS: Debian 10

Browser: Firefox latest

### Grafana platform?

A package manager (APT, YUM, BREW, etc.)

### Datasource(s)?

prometheus

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88136

**Comment by moxious** [comment]
**Summary**: The issue reports a slow load time for a Grafana dashboard after upgrading to version 11.0.0, where the load time increased from less than 1 second to approximately 7 seconds, despite fast query responses from Prometheus. Downgrading to version 10.4.3 resolves the issue, indicating a regression in the new Grafana version.

**Comment by moxious** [comment]
Hello @tonypowa, it seems like you're facing performance issues with dashboards after upgrading Grafana. Because the issue appears related to performance changes in a Grafana release, this seems most fitting for the **Frontend Platform project**. The developers there can look into potential regressions or performance impacts brought by the new version.

**Suggestion:**
- Please ensure to include detailed steps for reproduction and any relevant Grafana server logs.
- If possible, try profiling the dashboard load times using browser developer tools and attach the performance traces.

I'll tag this issue for review by the Frontend Platform team.

Thank you for reporting this!

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reporting this issue. In order to help us understand the problem with Grafana 11.0.0 and assist you more efficiently, we need a bit more information. Could you please provide the following details? 

1. Can you share the exact queries or a sanitized version that is causing the slow dashboard load times? This may help identify if a specific query is at fault.
2. Are there any console errors in the browser developer tools when the dashboard is loading? If yes, please provide the error messages or screenshots.
3. Could you provide the relevant Grafana server logs around the time when the issue occurs? They might contain hints on what's causing the slowdown.
4. Is it possible that the issue is related to increased load or data size that the dashboard has to handle compared to previous versions?
5. Can you confirm if modifying the `scrape_interval` or `scrape_timeout` settings in Prometheus has any effect on the load time?
6. Have you noticed if the dashboard is slow only on the initial load or also when performing subsequent actions within the dashboard?

Any additional context around this issue or steps you might have already tried (besides the downgrade) could help with pinpointing the cause. Thank you again for your contribution to the community!
