### ISSUE TITLE
Dashboards: Unable to disable angularDeprecationUI feature using environment variables

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#364]
### What happened?

Setting the environment variable 

`GF_FEATURE_TOGGLES_ANGULARDEPRECATIONUI=False`

does not prevent the Angular deprecation warning popup.

It could be that this the wrong syntax, but it is not well documented how to use environment variables to disable feature toggles.

### What did you expect to happen?

No Angular deprecation warning is displayed when I open a dashboard with a deprecated panel.

### Did this work before?

No, I have not used the GF_FEATURE_TOGGLES env vars before Grafana v11.0, but I use env vars to do all the other Grafana configuration.

### How do we reproduce it?

1. Set env var GF_FEATURE_TOGGLES_ANGULARDEPRECATIONUI=False

2. Start Grafana

3. Create a dashboard with a panel visualization using Angular, for example FlowCharting

4. Observe warning

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: 11.0

Docker image: grafana/grafana-oss:11.0.0

### Grafana platform?

Docker

```[tasklist]
### Tasks
```

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88364

**Comment by moxious** [comment]
**Summary**: User tonypowa reports that despite setting the environment variable `GF_FEATURE_TOGGLES_ANGULARDEPRECATIONUI=False`, the Angular deprecation warning still appears in Grafana v11.0. The issue remains open, and it's unclear whether the problem lies with the syntax or the documentation of environment variables for feature toggles.

**Comment by moxious** [comment]
Hi @tonypowa, it sounds like you might be encountering an issue related to the Frontend Platform project, especially if the feature toggle isn't responding as expected in the UI. However, this might also be relevant for the Backend platform project, as it concerns the use of environment variables for configuration. It might be best to start with the Frontend Platform project since it directly affects the user interface.

```markdown
Please ensure you've spelled the environment variable correctly and that it's properly recognized by the Grafana instance. In case this doesn't resolve the issue, could you please provide any output logs that show how the environment variable is being processed on startup? That can help in pinpointing where the issue might be occurring.
```

The team will likely need more information to diagnose this properly, but I'll tag this issue as potentially affecting the Frontend Platform for now.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for providing a clear description of the issue with the `GF_FEATURE_TOGGLES_ANGULARDEPRECATIONUI` environment variable and the steps to reproduce it. To better assist you and address the problem, could you please provide us with additional information as listed below? This will help us verify the issue and look for a potential fix or workaround.

- Could you confirm that the environment variable is set correctly within the Docker container for Grafana? Sometimes, environment variables might not be set as expected due to Docker configurations. You can check this by running `env` or `printenv` within the container.
- Have you tried other variations of the environment variable, such as with different casing (e.g., `true` vs `True` vs `false` vs `False`)? Please provide the outcomes if you have.
- Can you include the logs from Grafana starting up, particularly any entries related to feature toggles or the environment variables being recognized?
- It might also be helpful if you could share any relevant parts of your Docker configuration, especially if you have a custom `docker-compose.yml` or Dockerfile that may influence the environment variable settings.

Once we have this information, we'll be better positioned to understand the issue and offer a solution. Thank you for your cooperation!
