### ISSUE TITLE
PyQt can't open grafana correctly

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#366]
Dear all:

 I'm working with grafana recently to show some figures and tables. While there're issues i found. When I try to open grafana url with PyQt，the fatal problem come out. My python code and the result as following

` 

 import sys

 from PyQt5.QtWidgets import QApplication, QMainWindow

 from PyQt5.QtCore import QUrl

 from PyQt5.QtWebEngineWidgets import QWebEngineView

 

 

 class GrafanaDashboard(QMainWindow):

 def __init__(self, grafana_url):

 super().__init__()

 

 self.browser = QWebEngineView()

 

 self.browser.load(QUrl(grafana_url))

 

 # clear all

 self.browser.page().profile().clearAllVisitedLinks()

 self.browser.page().profile().clearHttpCache()

 self.browser.page().profile().cookieStore().deleteAllCookies()

 

 # Connect the loadFinished signal to the handler function

 self.browser.loadFinished.connect(self.on_load_finished)

 

 self.setCentralWidget(self.browser)

 self.showMaximized()

 

 # Add a slot to handle the loadFinished signal

 def on_load_finished(self, success):

 # The success parameter indicates whether the page was loaded successfully

 if success:

 print("Page loaded successfully")

 else:

 print("Failed to load the page")

 

 

 if __name__ == '__main__':

 app = QApplication(sys.argv)

 grafana_url = 'http://10.1.160.133:3015'

 mainWin = GrafanaDashboard(grafana_url)

 mainWin.show()

 sys.exit(app.exec_())`

and the results show

![info1](https://github.com/grafana/grafana/assets/58569651/47bf39b7-c897-4daa-9dd6-f06a63866ec8)

I don't know the reason why it gets error. However, when the dashboard url is linked by webbrowser all is OK. Our group has decided to import PyQt to show the statistical tables and images with grafana dashboard url. This iussue bores us for a long time. If anyone who has sovled the same problem give me some useful imformation please. 

Thanks a lot.

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#88402

**Comment by moxious** [comment]
**Summary**: User tonypowa reports an issue with opening a Grafana URL in a PyQt application, with errors encountered during page loading. The problem persists despite the dashboard working correctly when accessed via a web browser. Assistance is sought from anyone who has resolved a similar issue.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reaching out to the community with your issue. To help pinpoint the problem you're facing with opening Grafana through PyQt, we need a bit more detailed information. Could you please provide the following additional details?

- What exactly is the 'fatal problem' that occurs? Are there any specific error messages, exceptions or crash logs that you can share?
- Can you confirm the version of PyQt you are using as well as the version of Grafana?
- What operating system and version are you running on your development machine?
- Does the problem occur consistently every time you run the code, or are there times when it successfully loads the Grafana dashboard?
- Providing the contents of the console output or error messages would be extremely helpful.
- Have you made any modifications to the default security settings of QWebEngineView that might be relevant to this issue?
- Since the screenshot link seems to be broken, could you please re-upload the image showing the outcome you're getting?

Once you provide more context and details, it will be easier for the community to assist you in resolving the issue.

**Comment by moxious** [comment]
Hi @tonypowa, it seems like your issue involves integrating Grafana with a PyQt application. This isn't directly related to Grafana's core functionality but appears to be more of an external application integration challenge. Nevertheless, your issue might be more effectively addressed by the Grafana App Platform project, as they might have insights into how the Grafana interface operates within external applications like PyQt. It may also be beneficial to share any error messages you're receiving to help diagnose the problem more accurately.
