### ISSUE TITLE
Alert urls: Grafana alert urls not working under subpath and reverse proxy

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#372]
### What happened?

Specific Grafana urls not working when serving Grafana under subpath.

Seems that the subpath is not populated in the links. This results to the links not working when using Reverse proxy.

### What did you expect to happen?

Expected for the subpath to be populated in the links.

**example:**

the alert rule annotation links ( dashboard , panel ) links are as follows:

- https://{{domain}}/d/a18ef1af1afad0e84dae9155710ec07c_acc

But they should also have the subpath populated

- https://{{domain}}/grafana/d/a18ef1af1afad0e84dae9155710ec07c_acc

![Screenshot from 2024-06-10 12-14-08](https://github.com/grafana/grafana/assets/170091073/f286edb9-d39c-447f-80d6-50896a4e6bb1)

### Did this work before?

Didn't work before.

Only works when using no reverse proxy.

### How do we reproduce it?

1. Setup grafana with subpath / reverse proxy

2. Create an alert , and link with panel ( Dashboard/panel annotation links )

3. Open the alerts ( https://intragate.ec.europa.eu/cc-grafana-prod/alerting/list)

4. Navigate to the created alert and expand

5. Try to click in one of the links ( Dashboard UID , Panel ID )

### Environment (with versions)?

Grafana: oss - 10.3.3

OS: Podman - Rhel 8

Browser: Chrome

### Grafana platform?

Docker

### Datasource(s)?

Prometheus

**Comment by moxious** [comment]
Hi @tonypowa, it seems like your issue relates to how Grafana handles subpaths under a reverse proxy setup. This could likely be an issue to address within the Backend Platform project, as it involves the server-side handling of URLs and proxy configurations. I suggest tagging this issue for the Backend Platform team to investigate further.

/label ~"Backend Platform project"

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa, thank you for reporting the issue with Grafana alert links under a subpath while using a reverse proxy. To help us further investigate and resolve the issue, could you please provide some additional details? 

- Could you confirm if you've set the `root_url` in your Grafana configuration to include the subpath, as per the [Grafana documentation](https://grafana.com/docs/grafana/latest/administration/configuration/#root_url)? 
- It would be helpful to see your reverse proxy configuration (please mask any sensitive information). 
- Have you seen any error messages in the Grafana server logs or the browser console when the issue occurs? If so, could you provide them? 
- Can you provide the full URL that is being generated, rather than the template example provided, to help us better understand the routing issue? If you have privacy concerns, please mask the domain. 
- Lastly, if possible, could you export and share a minimal dashboard JSON that reproduces the issue (with any sensitive information removed)? This will allow us to try and reproduce the issue in a similar environment. 

Once we have this information, we will be in a better position to assist you. Thanks!
