### ISSUE TITLE
Bug into the link to change the organizzation

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#375]
### What happened?

Grafana v10.4.1 

When I click on changing the organization as admin, it always sends me to the localhost. At the same time, it should lead me to myWebSite.com/orgId=xxxxx.

I think the problem is that they have programmed it as an "absolute link"=localhost instead of a "relative link".

It should be relative always, because sometimes i may have it in localhost, but others on the website.com

<img width="693" alt="error_grafana" src="https://github.com/grafana/grafana/assets/58390904/c49cc6ca-a11b-4f0b-b985-990dc4519558">

### What did you expect to happen?

to bring to the organization with the same link and not a localhost

### Did this work before?

no

### How do we reproduce it?

1. being admin

2. Grafana v10.4.1 

3. create different organization (and not being in localhost) than trying to switch between them

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#89321

**Comment by moxious** [comment]
**Elaboration**:


Thank you for reporting the issue with the change organization link in Grafana. To help us address this issue more efficiently, we'd appreciate if you could provide additional details to aid our investigation. Here are a few follow-up questions and requests for information: 

- Can you confirm if the issue is consistently reproducible on other browsers or systems, or if it is specific to a particular setup? 
- Please provide the exact version of your operating system and browsers where you have tested this. 
- As the screenshot link seems to be broken, could you please re-upload it or provide a correct link to the image so we can see the exact error you're encountering? 
- Have you made any configuration changes to Grafana that could affect how base URLs are constructed? If possible, share the relevant configuration section (with sensitive information redacted). 
- Could you provide the web server's (e.g., Nginx, Apache) configuration file if Grafana is being served through a proxy? This can greatly help in identifying any potential misconfigurations leading to absolute links.

Once you provide this information, we'll be better positioned to understand the problem and find a resolution. 

Thank you for your collaboration!
