### ISSUE TITLE
Grafana 11.1: when adding new datasource, long loading time 

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#381]
### What happened?

Hello Grafana team and community

I've upgraded Grafana 10.1 to 11.1, everything is working well so far except Add new data source.

My Grafana is in the private network, so can't connect to 34.120.177.193 (grafana.com), and I keep getting Proxy request timed out messages in logs. 

I have never had this issue with Grafana 10.1,

Thank you!

### What did you expect to happen?

-

### Did this work before?

I have never had this issue with Grafana 10.1,

### How do we reproduce it?

1. Click 'Add new data source' in the private network

2.

3.

### Environment (with versions)?

Grafana: 11.1 (docker image)

OS:

Browser:

### Grafana platform?

Docker

### Datasource(s)?

All

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#89866

**Comment by moxious** [comment]
Hi @tonypowa,

Thank you for reporting this issue. It sounds like you might be encountering a connectivity issue within the `Backend Platform project`, possibly related to changes in how datasources are handled in Grafana 11.1. It would be helpful to check if adding datasource functionality has been modified in the backend between versions 10.1 and 11.1.

In the meanwhile, as a workaround, you might want to look into whether Grafana settings or environment variables can be configured to skip attempts to contact `grafana.com` if that connectivity is not required for your datasources.

Team, can we tag this for the Backend Platform project for further investigation?

**Comment by moxious** [comment]
**Summary**: Issue 381 in Grafana 11.1 features long loading times when adding a new datasource due to a timeout while trying to connect to grafana.com from a private network, which did not occur in Grafana 10.1.

**Comment by moxious** [comment]
**Elaboration**:


Hello @tonypowa,

Thank you for reaching out and providing initial details regarding the issue you're facing with Grafana 11.1 when adding a new data source. We'll do our best to help you resolve this. To proceed efficiently, we need a bit more information:

1. **Detailed Grafana Logs:** Could you provide a snippet of the Grafana log showing the exact error message (including any stack traces or related errors) when you try to add a new data source?

2. **Configuration Settings:** Are there any proxy settings that you've configured within Grafana, or environment variables related to networking that could be relevant to this issue?

3. **Reproduction Steps:** You've started outlining the steps to reproduce the issue, but could you please provide additional details for step 2 and 3, if applicable?

4. **Network Configuration:** Since your Grafana instance is on a private network, are there any new network policies or firewalls that were introduced after upgrading to 11.1 which might be causing an inability to connect to external servers?

5. **Browser Details:** Which browser are you using, and have you tried this with different browsers?

6. **Timeout Settings:** Have you checked or modified any timeout settings in Grafana that could be relevant to this issue since the upgrade?

Once you provide these details, we'll have a better understanding of the situation and can work towards a resolution. If possible, please check if you can manually access `http://grafana.com` from within the network where the Grafana instance is located.

Thanks for your cooperation, and we look forward to assisting you further with this issue.

Best regards,
The Grafana Community Support Team
