### ISSUE TITLE
Grafana 404 error refreshing page

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#387]
### What happened?

running grafana-oss behind nginx ingress inside aks, grafana is working fine, when i acces to https://host/explore/metrics works fine , but if i refresh the page with f5 is displaying 404 error . Do You guys have any idea of what's happening?

### What did you expect to happen?

diplay the same page when refresh

### Did this work before?

Not

### How do we reproduce it?

1. Accesing to https://host/explore/metrics

2. refresh

3.

### Environment (with versions)?

Grafana:

OS:

Browser:

### Grafana platform?

Kubernetes

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90332

**Comment by moxious** [comment]
**Summary**: User tonypowa reported an issue with Grafana 404 error upon refreshing the page while running grafana-oss behind nginx on AKS, which was expected to reload the same page without errors.

**Comment by moxious** [comment]
Hi @tonypowa, this seems like an issue that might be related to the configuration of your reverse proxy rather than Grafana itself. Make sure your NGINX ingress is configured to pass through all URLs correctly to the Grafana service. The fact that direct navigation works but refresh doesn't often points to an issue with the NGINX setup rather than Grafana. 

However, if you believe it's an issue with Grafana's handling, this may be relevant to the **Explore project** or the **Grafana Operator Experience Squad** since it involves operation within Kubernetes. If your setup proves correct and you suspect a Grafana problem, providing more information about your Grafana version and potentially your NGINX config (redacted for sensitive information) could help the community assist you further.

**Comment by moxious** [comment]
**Elaboration**:


Hi @tonypowa, thank you for reaching out with your issue. It does look like you've hit an unusual behavior with Grafana, and I'd love to help you sort it out. But, to get a clearer picture of what might be causing the 404 error on refresh, there are a few additional pieces of information that could be really helpful. Could you please provide the following details?

- **Grafana version:** You mentioned you're running `grafana-oss`. Can you specify the exact version number?
- **OS and Browser details:** Which operating system are you using, and which browser (including version) is this issue occurring on?
- **Nginx Configuration:** The issue might be related to how Nginx is configured. Could you share the relevant portion of your Nginx configuration, particularly the parts handling `location` or rewrite rules?
- **Grafana Configuration:** Can you show us the relevant parts of your Grafana configuration, especially if you have made any custom settings for the `root_url` or server settings?
- **Ingress Details:** What Ingress Controller are you using, and can you provide its configuration details or any special annotations related to Grafana?
- **Logs:** Could you share the logs from Grafana and Nginz at the time when the error occurs? Look for any errors or messages that might indicate what's going on at the time of the 404.
- **Steps to Reproduce:** While you've given a basic outline, could you provide a more detailed set of steps, and confirm if this happens in all browsers and all instances of Grafana?

Having exact error messages, configurations, and steps to reproduce the issue will help our community and the maintainers to pinpoint the problem and provide you with a solution much faster.

Thank you for your collaboration, and we're looking forward to getting to the bottom of this!
