### ISSUE TITLE
Grafana 11.1 uses browser scrollbar instead of grafana scroll bar

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#390]
### What happened?

I opened grafana in edge and firefox, and the scrollbar is the respective scroll bar from the browser is used. 

Example, firefox 128:

Not only in plugins, but only as example:

![grafik](https://github.com/user-attachments/assets/bb7ab43c-5bff-4449-a346-2ce48be4cf5e)

### What did you expect to happen?

The grafana scrollbar should be used

### Did this work before?

grafana 9.x

### How do we reproduce it?

1. Open a grafana web page with scrollbar

### Environment (with versions)?

Grafana: 11.1.0

OS: Docker, Windows

Browser: Firefox, Edge

### Grafana platform?

Docker

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90586

**Comment by moxious** [comment]
**Elaboration**:


### Request for additional information

Hello @tonypowa,

Thank you for bringing this to our attention! We'd like to make sure we understand the issue clearly so we can address it properly. To help us get a clearer picture, could you please provide us with a few more details?

- **Steps to Reproduce**: You've mentioned the general step to open a Grafana web page with a scrollbar, but could you specify which dashboards or panels are affected? Are there any particular settings or a large number of panels that trigger the issue?

- **Expected Behavior**: Could you provide a screenshot from an older version of Grafana (e.g. 9.x), where the Grafana scrollbar is behaving as expected? This would help us understand the visual difference you are referring to.

- **Browser Details**: Are there any specific browser versions or settings that seem to affect the scrollbar behavior? Also, are browser extensions or themes active that might interfere?

- **Console Logs**: If possible, could you check the browser console for any errors or warnings when the issue occurs and provide us with the logs?

- **Configuration**: Is there any custom CSS or JavaScript included in your Grafana setup that could affect the scrollbars?

- **Grafana Configuration**: Are there specific settings in Grafana that were tweaked or customized from default that might be related to this issue?

Once we have this information, we'll be in a better position to investigate further and find a resolution.

Looking forward to your reply, and thank you for your cooperation!

**Comment by moxious** [comment]
Hi @tonypowa, thanks for reporting this issue. It seems like your concern is related to the user interface and how Grafana handles scrollbars across browsers. Based on the information you've provided, I believe this issue will get the proper attention in the **Frontend Platform project**. 

The team responsible for the frontend will have the context to address the scrollbar behavior across different browsers. If you haven't already, please make sure to include any console logs or additional information to help them replicate and troubleshoot the issue.

Thank you for contributing to Grafana!
