### ISSUE TITLE
Public Dashboard no longer refreshing as expected

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#391]
### What happened?

Public dashboard which has always refreshed as expected has stopped doing so with the most recent update (on grafana cloud). Tried re-saving and checking box to update the refresh to see if that fixed the issue, but did not fix it.

It doesn't seem to even try to refresh... the tickmarks that show on every panel when it's refreshing never even show on the public version.

### What did you expect to happen?

Public dashboard should honor the 60 second refresh like it used to.

### Did this work before?

Yes. I'm not sure which update on grafana cloud caused it. It seems potentially related to the update that changed the refresh/edit/save bar.

### How do we reproduce it?

1. Open public dashboard

2. Note that dashboard, which refreshes as expected when logged in, does not refresh when public link loaded

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: grafana.net

OS: Windows

Browser: Chrome and Edge both show same behavior

### Grafana platform?

I use Grafana Cloud

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90706

**Comment by moxious** [comment]
**Summary**: The public dashboard on Grafana Cloud is no longer refreshing every 60 seconds as expected following a recent update, and this issue persists despite attempts to re-save and enable the refresh setting. The problem is consistent across different browsers and was not an issue before the recent changes to the refresh/edit/save bar.

**Comment by moxious** [comment]
Hi @tonypowa, it looks like this issue is related to the dashboard functionality on Grafana Cloud. The best team to handle this seems to be the **Hosted Grafana project** as they are specialized in issues pertaining to the hosted services. Can you confirm if this occurs only for a specific dashboard or all public dashboards you have? Additionally, please provide the version of Grafana Cloud you're currently using if available.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for providing a detailed account of the issue you're facing with the public dashboard refresh functionality on Grafana Cloud. To help the maintainers understand and resolve the issue more effectively, could I ask you a few additional questions and for some clarifications? 

- Could you please tell us the exact version of Grafana you are using? It's essential to pinpoint if a specific update caused this issue.
- Is the lack of refresh for a specific dashboard, or is it happening across all public dashboards you have access to?
- Have you checked the Grafana server logs for any errors that occur when you try to access the public dashboard?
- Could you provide a screenshot or screen recording of the issue as it happens?
- It would be helpful to know if you've implemented any custom settings, scripts, or third-party plugins that might be influencing the auto-refresh functionality.
- Have you attempted to recreate the dashboard to see if the issue persists with anew setup?

Your cooperation is highly appreciated, and this additional information will be key to diagnosing the problem more quickly.
