### ISSUE TITLE
Saving Dashboards: Characters not allowed in Windows or Linux file names should not be allowed in dashboard names or folder names

### ISSUE THREAD

**Issue by tonypowa** [moxious/triage#401]
### What happened?

We use third-party software to archive and manage our dashboards outside of Grafana. For us, so far it's been happening with our own Python code used to process JSON files saved by Grafana Backup (https://pypi.org/project/grafana-backup/) and with OCI Registry as Storage (https://github.com/oras-project). In the end, the third party software will attempt to save a directory, however this save will fail when it encounters an invalid file name which is possible when such a file name is used as a Grafana dashboard or folder name.

Sample message from oras:

Error: failed to extract tar to C:\temp\org_platypus-hatchery: 

mkdir C:\temp\org_platypus-hatchery\dashboards\Inflation - US ZOO: NonAvian Data (Reptiles, Amphibians, etc): 

The directory name is invalid.

### What did you expect to happen?

When the user would attempt to create this new folder (Inflation - US ZOO: NonAvian Data (Reptiles, Amphibians, etc):) he/she should be prompted for an alternate name as this contains colons. Not valid in a Windows file name.

The following printable characters are not allowed in Windows file names:

< (less than)

> (greater than)

: (colon)

" (double quote)

/ (forward slash)

\ (backslash)

| (vertical bar or pipe)

? (question mark)

* (asterisk)

In Linux, which is less restrictive, only the

/ (forward slash)

is not permitted.

### Did this work before?

Always been there

### How do we reproduce it?

Save a dashboard with the file name and folder name containing disallowed characters

Folder name would be something like Turtles: Aquatic

Dashboard name would be something like Species: Red Eared Slider

### Is the bug inside a dashboard panel?

No

### Environment (with versions)?

Grafana: Several

OS: Windows 10

Browser: Several, Firefox, Chrome

### Grafana platform?

None

**Comment by tonypowa** [comment]
This issue is a test copy of an issue in another repo.  Original issue: https://github.com/grafana/grafana/issues/#90996

**Comment by moxious** [comment]
**Summary**: Issue #401 in an OPEN state by author tonypowa reports a problem where Grafana allows dashboard and folder names containing characters invalid for Windows or Linux file names, causing failures during saves with third-party software. The user expects the system to prompt for an alternate name when such invalid characters are used.

**Comment by moxious** [comment]
Hi @tonypowa, it seems like your issue pertains to the overall management and structuring of dashboards, including naming conventions which affects how they are stored and managed externally. Thus, this might be more related to the **Dashboards Sharing squad project**. I will label this issue so it can get the attention of the appropriate team.

**Comment by moxious** [comment]
**Elaboration**:


Thank you for the detailed report, @tonypowa. In order to suggest a potential fix or offer a workaround, could you please offer a little more information on a couple of points? It helps us to ensure we fully understand the scope and impact of the issue. Here are some questions I have after reading your report: 

1. Has this issue been discussed with the Grafana community, and if so, is there any existing consensus on how to handle invalid characters in dashboard and folder names?
2. Can you please specify which versions of Grafana you have noticed this behavior in, even if 'several', a couple of explicit version numbers or ranges would help us track the issue more accurately?
3. Could you provide an example of the Python code or a snippet that is used to process the JSON files saved by Grafana Backup, especially where it engages with the file system?
4. Have you experimented with any specific character filtering or sanitization in your code as a temporary solution, and if so, what were the results?
5. Is this issue observed consistently across multiple operating environments, or have there been any cases where the issue does not manifest?

We understand that some of this information might be sensitive, so please anonymize any details that you do not wish to disclose publicly. Thank you once again for contributing to the community, your cooperation is invaluable in resolving issues like this one.
